// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fatdemo.proto

package protobuf

import (
	
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EHitGroup int32

const (
	EHitGroup_EHG_Generic  EHitGroup = 0
	EHitGroup_EHG_Head     EHitGroup = 1
	EHitGroup_EHG_Chest    EHitGroup = 2
	EHitGroup_EHG_Stomach  EHitGroup = 3
	EHitGroup_EHG_LeftArm  EHitGroup = 4
	EHitGroup_EHG_RightArm EHitGroup = 5
	EHitGroup_EHG_LeftLeg  EHitGroup = 6
	EHitGroup_EHG_RightLeg EHitGroup = 7
	EHitGroup_EHG_Gear     EHitGroup = 8
	EHitGroup_EHG_Miss     EHitGroup = 9
)

// Enum value maps for EHitGroup.
var (
	EHitGroup_name = map[int32]string{
		0: "EHG_Generic",
		1: "EHG_Head",
		2: "EHG_Chest",
		3: "EHG_Stomach",
		4: "EHG_LeftArm",
		5: "EHG_RightArm",
		6: "EHG_LeftLeg",
		7: "EHG_RightLeg",
		8: "EHG_Gear",
		9: "EHG_Miss",
	}
	EHitGroup_value = map[string]int32{
		"EHG_Generic":  0,
		"EHG_Head":     1,
		"EHG_Chest":    2,
		"EHG_Stomach":  3,
		"EHG_LeftArm":  4,
		"EHG_RightArm": 5,
		"EHG_LeftLeg":  6,
		"EHG_RightLeg": 7,
		"EHG_Gear":     8,
		"EHG_Miss":     9,
	}
)

func (x EHitGroup) Enum() *EHitGroup {
	p := new(EHitGroup)
	*p = x
	return p
}

func (x EHitGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EHitGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_fatdemo_proto_enumTypes[0].Descriptor()
}

func (EHitGroup) Type() protoreflect.EnumType {
	return &file_fatdemo_proto_enumTypes[0]
}

func (x EHitGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EHitGroup) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EHitGroup(num)
	return nil
}

// Deprecated: Use EHitGroup.Descriptor instead.
func (EHitGroup) EnumDescriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{0}
}

type ETeam int32

const (
	ETeam_ET_Unknown   ETeam = 0
	ETeam_ET_Spectator ETeam = 1
	ETeam_ET_Terrorist ETeam = 2
	ETeam_ET_CT        ETeam = 3
)

// Enum value maps for ETeam.
var (
	ETeam_name = map[int32]string{
		0: "ET_Unknown",
		1: "ET_Spectator",
		2: "ET_Terrorist",
		3: "ET_CT",
	}
	ETeam_value = map[string]int32{
		"ET_Unknown":   0,
		"ET_Spectator": 1,
		"ET_Terrorist": 2,
		"ET_CT":        3,
	}
)

func (x ETeam) Enum() *ETeam {
	p := new(ETeam)
	*p = x
	return p
}

func (x ETeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ETeam) Descriptor() protoreflect.EnumDescriptor {
	return file_fatdemo_proto_enumTypes[1].Descriptor()
}

func (ETeam) Type() protoreflect.EnumType {
	return &file_fatdemo_proto_enumTypes[1]
}

func (x ETeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ETeam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ETeam(num)
	return nil
}

// Deprecated: Use ETeam.Descriptor instead.
func (ETeam) EnumDescriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{1}
}

type EWeaponType int32

const (
	EWeaponType_EWT_Knife         EWeaponType = 0
	EWeaponType_EWT_Pistol        EWeaponType = 1
	EWeaponType_EWT_SubMachineGun EWeaponType = 2
	EWeaponType_EWT_Rifle         EWeaponType = 3
	EWeaponType_EWT_Shotgun       EWeaponType = 4
	EWeaponType_EWT_SniperRifle   EWeaponType = 5
	EWeaponType_EWT_MachineGun    EWeaponType = 6
	EWeaponType_EWT_C4            EWeaponType = 7
	EWeaponType_EWT_Grenade       EWeaponType = 8
	EWeaponType_EWT_Equipment     EWeaponType = 9
	EWeaponType_EWT_StackableItem EWeaponType = 10
	EWeaponType_EWT_Unknown       EWeaponType = 11
)

// Enum value maps for EWeaponType.
var (
	EWeaponType_name = map[int32]string{
		0:  "EWT_Knife",
		1:  "EWT_Pistol",
		2:  "EWT_SubMachineGun",
		3:  "EWT_Rifle",
		4:  "EWT_Shotgun",
		5:  "EWT_SniperRifle",
		6:  "EWT_MachineGun",
		7:  "EWT_C4",
		8:  "EWT_Grenade",
		9:  "EWT_Equipment",
		10: "EWT_StackableItem",
		11: "EWT_Unknown",
	}
	EWeaponType_value = map[string]int32{
		"EWT_Knife":         0,
		"EWT_Pistol":        1,
		"EWT_SubMachineGun": 2,
		"EWT_Rifle":         3,
		"EWT_Shotgun":       4,
		"EWT_SniperRifle":   5,
		"EWT_MachineGun":    6,
		"EWT_C4":            7,
		"EWT_Grenade":       8,
		"EWT_Equipment":     9,
		"EWT_StackableItem": 10,
		"EWT_Unknown":       11,
	}
)

func (x EWeaponType) Enum() *EWeaponType {
	p := new(EWeaponType)
	*p = x
	return p
}

func (x EWeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EWeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_fatdemo_proto_enumTypes[2].Descriptor()
}

func (EWeaponType) Type() protoreflect.EnumType {
	return &file_fatdemo_proto_enumTypes[2]
}

func (x EWeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EWeaponType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EWeaponType(num)
	return nil
}

// Deprecated: Use EWeaponType.Descriptor instead.
func (EWeaponType) EnumDescriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{2}
}

type MLDict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	ValString     *string                `protobuf:"bytes,2,opt,name=val_string,json=valString" json:"val_string,omitempty"`
	ValInt        *int32                 `protobuf:"varint,3,opt,name=val_int,json=valInt" json:"val_int,omitempty"`
	ValFloat      *float32               `protobuf:"fixed32,4,opt,name=val_float,json=valFloat" json:"val_float,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLDict) Reset() {
	*x = MLDict{}
	mi := &file_fatdemo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLDict) ProtoMessage() {}

func (x *MLDict) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLDict.ProtoReflect.Descriptor instead.
func (*MLDict) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{0}
}

func (x *MLDict) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *MLDict) GetValString() string {
	if x != nil && x.ValString != nil {
		return *x.ValString
	}
	return ""
}

func (x *MLDict) GetValInt() int32 {
	if x != nil && x.ValInt != nil {
		return *x.ValInt
	}
	return 0
}

func (x *MLDict) GetValFloat() float32 {
	if x != nil && x.ValFloat != nil {
		return *x.ValFloat
	}
	return 0
}

type MLEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     *string                `protobuf:"bytes,1,opt,name=event_name,json=eventName" json:"event_name,omitempty"`
	Data          []*MLDict              `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLEvent) Reset() {
	*x = MLEvent{}
	mi := &file_fatdemo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLEvent) ProtoMessage() {}

func (x *MLEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLEvent.ProtoReflect.Descriptor instead.
func (*MLEvent) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{1}
}

func (x *MLEvent) GetEventName() string {
	if x != nil && x.EventName != nil {
		return *x.EventName
	}
	return ""
}

func (x *MLEvent) GetData() []*MLDict {
	if x != nil {
		return x.Data
	}
	return nil
}

type MLMatchState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameMode      *string                `protobuf:"bytes,1,opt,name=game_mode,json=gameMode" json:"game_mode,omitempty"`
	Phase         *string                `protobuf:"bytes,2,opt,name=phase" json:"phase,omitempty"`
	Round         *int32                 `protobuf:"varint,3,opt,name=round" json:"round,omitempty"`
	ScoreCt       *int32                 `protobuf:"varint,4,opt,name=score_ct,json=scoreCt" json:"score_ct,omitempty"`
	ScoreT        *int32                 `protobuf:"varint,5,opt,name=score_t,json=scoreT" json:"score_t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLMatchState) Reset() {
	*x = MLMatchState{}
	mi := &file_fatdemo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLMatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLMatchState) ProtoMessage() {}

func (x *MLMatchState) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLMatchState.ProtoReflect.Descriptor instead.
func (*MLMatchState) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{2}
}

func (x *MLMatchState) GetGameMode() string {
	if x != nil && x.GameMode != nil {
		return *x.GameMode
	}
	return ""
}

func (x *MLMatchState) GetPhase() string {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return ""
}

func (x *MLMatchState) GetRound() int32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *MLMatchState) GetScoreCt() int32 {
	if x != nil && x.ScoreCt != nil {
		return *x.ScoreCt
	}
	return 0
}

func (x *MLMatchState) GetScoreT() int32 {
	if x != nil && x.ScoreT != nil {
		return *x.ScoreT
	}
	return 0
}

type MLRoundState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         *string                `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	WinTeam       *ETeam                 `protobuf:"varint,2,opt,name=win_team,json=winTeam,enum=ETeam,def=0" json:"win_team,omitempty"`
	BombState     *string                `protobuf:"bytes,3,opt,name=bomb_state,json=bombState" json:"bomb_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for MLRoundState fields.
const (
	Default_MLRoundState_WinTeam = ETeam_ET_Unknown
)

func (x *MLRoundState) Reset() {
	*x = MLRoundState{}
	mi := &file_fatdemo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLRoundState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLRoundState) ProtoMessage() {}

func (x *MLRoundState) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLRoundState.ProtoReflect.Descriptor instead.
func (*MLRoundState) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{3}
}

func (x *MLRoundState) GetPhase() string {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return ""
}

func (x *MLRoundState) GetWinTeam() ETeam {
	if x != nil && x.WinTeam != nil {
		return *x.WinTeam
	}
	return Default_MLRoundState_WinTeam
}

func (x *MLRoundState) GetBombState() string {
	if x != nil && x.BombState != nil {
		return *x.BombState
	}
	return ""
}

type MLWeaponState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *int32                 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type          *EWeaponType           `protobuf:"varint,3,opt,name=type,enum=EWeaponType,def=0" json:"type,omitempty"`
	AmmoClip      *int32                 `protobuf:"varint,4,opt,name=ammo_clip,json=ammoClip" json:"ammo_clip,omitempty"`
	AmmoClipMax   *int32                 `protobuf:"varint,5,opt,name=ammo_clip_max,json=ammoClipMax" json:"ammo_clip_max,omitempty"`
	AmmoReserve   *int32                 `protobuf:"varint,6,opt,name=ammo_reserve,json=ammoReserve" json:"ammo_reserve,omitempty"`
	State         *string                `protobuf:"bytes,7,opt,name=state" json:"state,omitempty"`
	RecoilIndex   *float32               `protobuf:"fixed32,8,opt,name=recoil_index,json=recoilIndex" json:"recoil_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for MLWeaponState fields.
const (
	Default_MLWeaponState_Type = EWeaponType_EWT_Knife
)

func (x *MLWeaponState) Reset() {
	*x = MLWeaponState{}
	mi := &file_fatdemo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLWeaponState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLWeaponState) ProtoMessage() {}

func (x *MLWeaponState) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLWeaponState.ProtoReflect.Descriptor instead.
func (*MLWeaponState) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{4}
}

func (x *MLWeaponState) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *MLWeaponState) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MLWeaponState) GetType() EWeaponType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_MLWeaponState_Type
}

func (x *MLWeaponState) GetAmmoClip() int32 {
	if x != nil && x.AmmoClip != nil {
		return *x.AmmoClip
	}
	return 0
}

func (x *MLWeaponState) GetAmmoClipMax() int32 {
	if x != nil && x.AmmoClipMax != nil {
		return *x.AmmoClipMax
	}
	return 0
}

func (x *MLWeaponState) GetAmmoReserve() int32 {
	if x != nil && x.AmmoReserve != nil {
		return *x.AmmoReserve
	}
	return 0
}

func (x *MLWeaponState) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *MLWeaponState) GetRecoilIndex() float32 {
	if x != nil && x.RecoilIndex != nil {
		return *x.RecoilIndex
	}
	return 0
}

type MLPlayerState struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	AccountId     *int32                             `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	PlayerSlot    *int32                             `protobuf:"varint,2,opt,name=player_slot,json=playerSlot,def=-1" json:"player_slot,omitempty"`
	Entindex      *int32                             `protobuf:"varint,3,opt,name=entindex" json:"entindex,omitempty"`
	Name          *string                            `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Clan          *string                            `protobuf:"bytes,5,opt,name=clan" json:"clan,omitempty"`
	Team          *ETeam                             `protobuf:"varint,6,opt,name=team,enum=ETeam,def=0" json:"team,omitempty"`
	Abspos        *CMsgVector `protobuf:"bytes,7,opt,name=abspos" json:"abspos,omitempty"`
	Eyeangle      *CMsgQAngle `protobuf:"bytes,8,opt,name=eyeangle" json:"eyeangle,omitempty"`
	EyeangleFwd   *CMsgVector `protobuf:"bytes,9,opt,name=eyeangle_fwd,json=eyeangleFwd" json:"eyeangle_fwd,omitempty"`
	Health        *int32                             `protobuf:"varint,10,opt,name=health" json:"health,omitempty"`
	Armor         *int32                             `protobuf:"varint,11,opt,name=armor" json:"armor,omitempty"`
	Flashed       *float32                           `protobuf:"fixed32,12,opt,name=flashed" json:"flashed,omitempty"`
	Smoked        *float32                           `protobuf:"fixed32,13,opt,name=smoked" json:"smoked,omitempty"`
	Money         *int32                             `protobuf:"varint,14,opt,name=money" json:"money,omitempty"`
	RoundKills    *int32                             `protobuf:"varint,15,opt,name=round_kills,json=roundKills" json:"round_kills,omitempty"`
	RoundKillhs   *int32                             `protobuf:"varint,16,opt,name=round_killhs,json=roundKillhs" json:"round_killhs,omitempty"`
	Burning       *float32                           `protobuf:"fixed32,17,opt,name=burning" json:"burning,omitempty"`
	Helmet        *bool                              `protobuf:"varint,18,opt,name=helmet" json:"helmet,omitempty"`
	DefuseKit     *bool                              `protobuf:"varint,19,opt,name=defuse_kit,json=defuseKit" json:"defuse_kit,omitempty"`
	Weapons       []*MLWeaponState                   `protobuf:"bytes,20,rep,name=weapons" json:"weapons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for MLPlayerState fields.
const (
	Default_MLPlayerState_PlayerSlot = int32(-1)
	Default_MLPlayerState_Team       = ETeam_ET_Unknown
)

func (x *MLPlayerState) Reset() {
	*x = MLPlayerState{}
	mi := &file_fatdemo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLPlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLPlayerState) ProtoMessage() {}

func (x *MLPlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLPlayerState.ProtoReflect.Descriptor instead.
func (*MLPlayerState) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{5}
}

func (x *MLPlayerState) GetAccountId() int32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *MLPlayerState) GetPlayerSlot() int32 {
	if x != nil && x.PlayerSlot != nil {
		return *x.PlayerSlot
	}
	return Default_MLPlayerState_PlayerSlot
}

func (x *MLPlayerState) GetEntindex() int32 {
	if x != nil && x.Entindex != nil {
		return *x.Entindex
	}
	return 0
}

func (x *MLPlayerState) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MLPlayerState) GetClan() string {
	if x != nil && x.Clan != nil {
		return *x.Clan
	}
	return ""
}

func (x *MLPlayerState) GetTeam() ETeam {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return Default_MLPlayerState_Team
}

func (x *MLPlayerState) GetAbspos() *CMsgVector {
	if x != nil {
		return x.Abspos
	}
	return nil
}

func (x *MLPlayerState) GetEyeangle() *CMsgQAngle {
	if x != nil {
		return x.Eyeangle
	}
	return nil
}

func (x *MLPlayerState) GetEyeangleFwd() *CMsgVector {
	if x != nil {
		return x.EyeangleFwd
	}
	return nil
}

func (x *MLPlayerState) GetHealth() int32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *MLPlayerState) GetArmor() int32 {
	if x != nil && x.Armor != nil {
		return *x.Armor
	}
	return 0
}

func (x *MLPlayerState) GetFlashed() float32 {
	if x != nil && x.Flashed != nil {
		return *x.Flashed
	}
	return 0
}

func (x *MLPlayerState) GetSmoked() float32 {
	if x != nil && x.Smoked != nil {
		return *x.Smoked
	}
	return 0
}

func (x *MLPlayerState) GetMoney() int32 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

func (x *MLPlayerState) GetRoundKills() int32 {
	if x != nil && x.RoundKills != nil {
		return *x.RoundKills
	}
	return 0
}

func (x *MLPlayerState) GetRoundKillhs() int32 {
	if x != nil && x.RoundKillhs != nil {
		return *x.RoundKillhs
	}
	return 0
}

func (x *MLPlayerState) GetBurning() float32 {
	if x != nil && x.Burning != nil {
		return *x.Burning
	}
	return 0
}

func (x *MLPlayerState) GetHelmet() bool {
	if x != nil && x.Helmet != nil {
		return *x.Helmet
	}
	return false
}

func (x *MLPlayerState) GetDefuseKit() bool {
	if x != nil && x.DefuseKit != nil {
		return *x.DefuseKit
	}
	return false
}

func (x *MLPlayerState) GetWeapons() []*MLWeaponState {
	if x != nil {
		return x.Weapons
	}
	return nil
}

type MLGameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *MLMatchState          `protobuf:"bytes,1,opt,name=match" json:"match,omitempty"`
	Round         *MLRoundState          `protobuf:"bytes,2,opt,name=round" json:"round,omitempty"`
	Players       []*MLPlayerState       `protobuf:"bytes,3,rep,name=players" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLGameState) Reset() {
	*x = MLGameState{}
	mi := &file_fatdemo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLGameState) ProtoMessage() {}

func (x *MLGameState) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLGameState.ProtoReflect.Descriptor instead.
func (*MLGameState) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{6}
}

func (x *MLGameState) GetMatch() *MLMatchState {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *MLGameState) GetRound() *MLRoundState {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *MLGameState) GetPlayers() []*MLPlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type MLDemoHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapName       *string                `protobuf:"bytes,1,opt,name=map_name,json=mapName" json:"map_name,omitempty"`
	TickRate      *int32                 `protobuf:"varint,2,opt,name=tick_rate,json=tickRate" json:"tick_rate,omitempty"`
	Version       *uint32                `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	SteamUniverse *uint32                `protobuf:"varint,4,opt,name=steam_universe,json=steamUniverse" json:"steam_universe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLDemoHeader) Reset() {
	*x = MLDemoHeader{}
	mi := &file_fatdemo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLDemoHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLDemoHeader) ProtoMessage() {}

func (x *MLDemoHeader) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLDemoHeader.ProtoReflect.Descriptor instead.
func (*MLDemoHeader) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{7}
}

func (x *MLDemoHeader) GetMapName() string {
	if x != nil && x.MapName != nil {
		return *x.MapName
	}
	return ""
}

func (x *MLDemoHeader) GetTickRate() int32 {
	if x != nil && x.TickRate != nil {
		return *x.TickRate
	}
	return 0
}

func (x *MLDemoHeader) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *MLDemoHeader) GetSteamUniverse() uint32 {
	if x != nil && x.SteamUniverse != nil {
		return *x.SteamUniverse
	}
	return 0
}

type MLTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickCount     *int32                 `protobuf:"varint,1,opt,name=tick_count,json=tickCount" json:"tick_count,omitempty"`
	State         *MLGameState           `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Events        []*MLEvent             `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLTick) Reset() {
	*x = MLTick{}
	mi := &file_fatdemo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLTick) ProtoMessage() {}

func (x *MLTick) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLTick.ProtoReflect.Descriptor instead.
func (*MLTick) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{8}
}

func (x *MLTick) GetTickCount() int32 {
	if x != nil && x.TickCount != nil {
		return *x.TickCount
	}
	return 0
}

func (x *MLTick) GetState() *MLGameState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *MLTick) GetEvents() []*MLEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type VacNetShot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SteamidPlayer        *uint64                `protobuf:"fixed64,1,opt,name=steamid_player,json=steamidPlayer" json:"steamid_player,omitempty"`
	RoundNumber          *int32                 `protobuf:"varint,2,opt,name=round_number,json=roundNumber" json:"round_number,omitempty"`
	HitType              *int32                 `protobuf:"varint,3,opt,name=hit_type,json=hitType" json:"hit_type,omitempty"`
	WeaponType           *int32                 `protobuf:"varint,4,opt,name=weapon_type,json=weaponType" json:"weapon_type,omitempty"`
	DistanceToHurtTarget *float32               `protobuf:"fixed32,5,opt,name=distance_to_hurt_target,json=distanceToHurtTarget" json:"distance_to_hurt_target,omitempty"`
	DeltaYawWindow       []float32              `protobuf:"fixed32,6,rep,name=delta_yaw_window,json=deltaYawWindow" json:"delta_yaw_window,omitempty"`
	DeltaPitchWindow     []float32              `protobuf:"fixed32,7,rep,name=delta_pitch_window,json=deltaPitchWindow" json:"delta_pitch_window,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VacNetShot) Reset() {
	*x = VacNetShot{}
	mi := &file_fatdemo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacNetShot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacNetShot) ProtoMessage() {}

func (x *VacNetShot) ProtoReflect() protoreflect.Message {
	mi := &file_fatdemo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacNetShot.ProtoReflect.Descriptor instead.
func (*VacNetShot) Descriptor() ([]byte, []int) {
	return file_fatdemo_proto_rawDescGZIP(), []int{9}
}

func (x *VacNetShot) GetSteamidPlayer() uint64 {
	if x != nil && x.SteamidPlayer != nil {
		return *x.SteamidPlayer
	}
	return 0
}

func (x *VacNetShot) GetRoundNumber() int32 {
	if x != nil && x.RoundNumber != nil {
		return *x.RoundNumber
	}
	return 0
}

func (x *VacNetShot) GetHitType() int32 {
	if x != nil && x.HitType != nil {
		return *x.HitType
	}
	return 0
}

func (x *VacNetShot) GetWeaponType() int32 {
	if x != nil && x.WeaponType != nil {
		return *x.WeaponType
	}
	return 0
}

func (x *VacNetShot) GetDistanceToHurtTarget() float32 {
	if x != nil && x.DistanceToHurtTarget != nil {
		return *x.DistanceToHurtTarget
	}
	return 0
}

func (x *VacNetShot) GetDeltaYawWindow() []float32 {
	if x != nil {
		return x.DeltaYawWindow
	}
	return nil
}

func (x *VacNetShot) GetDeltaPitchWindow() []float32 {
	if x != nil {
		return x.DeltaPitchWindow
	}
	return nil
}

var File_fatdemo_proto protoreflect.FileDescriptor

const file_fatdemo_proto_rawDesc = "" +
	"\n" +
	"\rfatdemo.proto\x1a\x16networkbasetypes.proto\"o\n" +
	"\x06MLDict\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"val_string\x18\x02 \x01(\tR\tvalString\x12\x17\n" +
	"\aval_int\x18\x03 \x01(\x05R\x06valInt\x12\x1b\n" +
	"\tval_float\x18\x04 \x01(\x02R\bvalFloat\"E\n" +
	"\aMLEvent\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1b\n" +
	"\x04data\x18\x02 \x03(\v2\a.MLDictR\x04data\"\x8b\x01\n" +
	"\fMLMatchState\x12\x1b\n" +
	"\tgame_mode\x18\x01 \x01(\tR\bgameMode\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12\x19\n" +
	"\bscore_ct\x18\x04 \x01(\x05R\ascoreCt\x12\x17\n" +
	"\ascore_t\x18\x05 \x01(\x05R\x06scoreT\"r\n" +
	"\fMLRoundState\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12-\n" +
	"\bwin_team\x18\x02 \x01(\x0e2\x06.ETeam:\n" +
	"ET_UnknownR\awinTeam\x12\x1d\n" +
	"\n" +
	"bomb_state\x18\x03 \x01(\tR\tbombState\"\x83\x02\n" +
	"\rMLWeaponState\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\f.EWeaponType:\tEWT_KnifeR\x04type\x12\x1b\n" +
	"\tammo_clip\x18\x04 \x01(\x05R\bammoClip\x12\"\n" +
	"\rammo_clip_max\x18\x05 \x01(\x05R\vammoClipMax\x12!\n" +
	"\fammo_reserve\x18\x06 \x01(\x05R\vammoReserve\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12!\n" +
	"\frecoil_index\x18\b \x01(\x02R\vrecoilIndex\"\xf2\x04\n" +
	"\rMLPlayerState\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12#\n" +
	"\vplayer_slot\x18\x02 \x01(\x05:\x02-1R\n" +
	"playerSlot\x12\x1a\n" +
	"\bentindex\x18\x03 \x01(\x05R\bentindex\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04clan\x18\x05 \x01(\tR\x04clan\x12&\n" +
	"\x04team\x18\x06 \x01(\x0e2\x06.ETeam:\n" +
	"ET_UnknownR\x04team\x12#\n" +
	"\x06abspos\x18\a \x01(\v2\v.CMsgVectorR\x06abspos\x12'\n" +
	"\beyeangle\x18\b \x01(\v2\v.CMsgQAngleR\beyeangle\x12.\n" +
	"\feyeangle_fwd\x18\t \x01(\v2\v.CMsgVectorR\veyeangleFwd\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\x05R\x06health\x12\x14\n" +
	"\x05armor\x18\v \x01(\x05R\x05armor\x12\x18\n" +
	"\aflashed\x18\f \x01(\x02R\aflashed\x12\x16\n" +
	"\x06smoked\x18\r \x01(\x02R\x06smoked\x12\x14\n" +
	"\x05money\x18\x0e \x01(\x05R\x05money\x12\x1f\n" +
	"\vround_kills\x18\x0f \x01(\x05R\n" +
	"roundKills\x12!\n" +
	"\fround_killhs\x18\x10 \x01(\x05R\vroundKillhs\x12\x18\n" +
	"\aburning\x18\x11 \x01(\x02R\aburning\x12\x16\n" +
	"\x06helmet\x18\x12 \x01(\bR\x06helmet\x12\x1d\n" +
	"\n" +
	"defuse_kit\x18\x13 \x01(\bR\tdefuseKit\x12(\n" +
	"\aweapons\x18\x14 \x03(\v2\x0e.MLWeaponStateR\aweapons\"\x81\x01\n" +
	"\vMLGameState\x12#\n" +
	"\x05match\x18\x01 \x01(\v2\r.MLMatchStateR\x05match\x12#\n" +
	"\x05round\x18\x02 \x01(\v2\r.MLRoundStateR\x05round\x12(\n" +
	"\aplayers\x18\x03 \x03(\v2\x0e.MLPlayerStateR\aplayers\"\x87\x01\n" +
	"\fMLDemoHeader\x12\x19\n" +
	"\bmap_name\x18\x01 \x01(\tR\amapName\x12\x1b\n" +
	"\ttick_rate\x18\x02 \x01(\x05R\btickRate\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12%\n" +
	"\x0esteam_universe\x18\x04 \x01(\rR\rsteamUniverse\"m\n" +
	"\x06MLTick\x12\x1d\n" +
	"\n" +
	"tick_count\x18\x01 \x01(\x05R\ttickCount\x12\"\n" +
	"\x05state\x18\x02 \x01(\v2\f.MLGameStateR\x05state\x12 \n" +
	"\x06events\x18\x03 \x03(\v2\b.MLEventR\x06events\"\xa1\x02\n" +
	"\n" +
	"VacNetShot\x12%\n" +
	"\x0esteamid_player\x18\x01 \x01(\x06R\rsteamidPlayer\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12\x19\n" +
	"\bhit_type\x18\x03 \x01(\x05R\ahitType\x12\x1f\n" +
	"\vweapon_type\x18\x04 \x01(\x05R\n" +
	"weaponType\x125\n" +
	"\x17distance_to_hurt_target\x18\x05 \x01(\x02R\x14distanceToHurtTarget\x12(\n" +
	"\x10delta_yaw_window\x18\x06 \x03(\x02R\x0edeltaYawWindow\x12,\n" +
	"\x12delta_pitch_window\x18\a \x03(\x02R\x10deltaPitchWindow*\xac\x01\n" +
	"\tEHitGroup\x12\x0f\n" +
	"\vEHG_Generic\x10\x00\x12\f\n" +
	"\bEHG_Head\x10\x01\x12\r\n" +
	"\tEHG_Chest\x10\x02\x12\x0f\n" +
	"\vEHG_Stomach\x10\x03\x12\x0f\n" +
	"\vEHG_LeftArm\x10\x04\x12\x10\n" +
	"\fEHG_RightArm\x10\x05\x12\x0f\n" +
	"\vEHG_LeftLeg\x10\x06\x12\x10\n" +
	"\fEHG_RightLeg\x10\a\x12\f\n" +
	"\bEHG_Gear\x10\b\x12\f\n" +
	"\bEHG_Miss\x10\t*F\n" +
	"\x05ETeam\x12\x0e\n" +
	"\n" +
	"ET_Unknown\x10\x00\x12\x10\n" +
	"\fET_Spectator\x10\x01\x12\x10\n" +
	"\fET_Terrorist\x10\x02\x12\t\n" +
	"\x05ET_CT\x10\x03*\xe4\x01\n" +
	"\vEWeaponType\x12\r\n" +
	"\tEWT_Knife\x10\x00\x12\x0e\n" +
	"\n" +
	"EWT_Pistol\x10\x01\x12\x15\n" +
	"\x11EWT_SubMachineGun\x10\x02\x12\r\n" +
	"\tEWT_Rifle\x10\x03\x12\x0f\n" +
	"\vEWT_Shotgun\x10\x04\x12\x13\n" +
	"\x0fEWT_SniperRifle\x10\x05\x12\x12\n" +
	"\x0eEWT_MachineGun\x10\x06\x12\n" +
	"\n" +
	"\x06EWT_C4\x10\a\x12\x0f\n" +
	"\vEWT_Grenade\x10\b\x12\x11\n" +
	"\rEWT_Equipment\x10\t\x12\x15\n" +
	"\x11EWT_StackableItem\x10\n" +
	"\x12\x0f\n" +
	"\vEWT_Unknown\x10\v"

var (
	file_fatdemo_proto_rawDescOnce sync.Once
	file_fatdemo_proto_rawDescData []byte
)

func file_fatdemo_proto_rawDescGZIP() []byte {
	file_fatdemo_proto_rawDescOnce.Do(func() {
		file_fatdemo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fatdemo_proto_rawDesc), len(file_fatdemo_proto_rawDesc)))
	})
	return file_fatdemo_proto_rawDescData
}

var file_fatdemo_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fatdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fatdemo_proto_goTypes = []any{
	(EHitGroup)(0),                            // 0: EHitGroup
	(ETeam)(0),                                // 1: ETeam
	(EWeaponType)(0),                          // 2: EWeaponType
	(*MLDict)(nil),                            // 3: MLDict
	(*MLEvent)(nil),                           // 4: MLEvent
	(*MLMatchState)(nil),                      // 5: MLMatchState
	(*MLRoundState)(nil),                      // 6: MLRoundState
	(*MLWeaponState)(nil),                     // 7: MLWeaponState
	(*MLPlayerState)(nil),                     // 8: MLPlayerState
	(*MLGameState)(nil),                       // 9: MLGameState
	(*MLDemoHeader)(nil),                      // 10: MLDemoHeader
	(*MLTick)(nil),                            // 11: MLTick
	(*VacNetShot)(nil),                        // 12: VacNetShot
	(*CMsgVector)(nil), // 13: CMsgVector
	(*CMsgQAngle)(nil), // 14: CMsgQAngle
}
var file_fatdemo_proto_depIdxs = []int32{
	3,  // 0: MLEvent.data:type_name -> MLDict
	1,  // 1: MLRoundState.win_team:type_name -> ETeam
	2,  // 2: MLWeaponState.type:type_name -> EWeaponType
	1,  // 3: MLPlayerState.team:type_name -> ETeam
	13, // 4: MLPlayerState.abspos:type_name -> CMsgVector
	14, // 5: MLPlayerState.eyeangle:type_name -> CMsgQAngle
	13, // 6: MLPlayerState.eyeangle_fwd:type_name -> CMsgVector
	7,  // 7: MLPlayerState.weapons:type_name -> MLWeaponState
	5,  // 8: MLGameState.match:type_name -> MLMatchState
	6,  // 9: MLGameState.round:type_name -> MLRoundState
	8,  // 10: MLGameState.players:type_name -> MLPlayerState
	9,  // 11: MLTick.state:type_name -> MLGameState
	4,  // 12: MLTick.events:type_name -> MLEvent
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_fatdemo_proto_init() }
func file_fatdemo_proto_init() {
	if File_fatdemo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fatdemo_proto_rawDesc), len(file_fatdemo_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fatdemo_proto_goTypes,
		DependencyIndexes: file_fatdemo_proto_depIdxs,
		EnumInfos:         file_fatdemo_proto_enumTypes,
		MessageInfos:      file_fatdemo_proto_msgTypes,
	}.Build()
	File_fatdemo_proto = out.File
	file_fatdemo_proto_goTypes = nil
	file_fatdemo_proto_depIdxs = nil
}
