// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: network_connection.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptor_proto "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ENetworkDisconnectionReason int32

const (
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_INVALID                          ENetworkDisconnectionReason = 0
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SHUTDOWN                         ENetworkDisconnectionReason = 1
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DISCONNECT_BY_USER               ENetworkDisconnectionReason = 2
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DISCONNECT_BY_SERVER             ENetworkDisconnectionReason = 3
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_LOST                             ENetworkDisconnectionReason = 4
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_OVERFLOW                         ENetworkDisconnectionReason = 5
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_BANNED                     ENetworkDisconnectionReason = 6
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_INUSE                      ENetworkDisconnectionReason = 7
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_TICKET                     ENetworkDisconnectionReason = 8
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_LOGON                      ENetworkDisconnectionReason = 9
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_AUTHCANCELLED              ENetworkDisconnectionReason = 10
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED            ENetworkDisconnectionReason = 11
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_AUTHINVALID                ENetworkDisconnectionReason = 12
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_VACBANSTATE                ENetworkDisconnectionReason = 13
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE        ENetworkDisconnectionReason = 14
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT         ENetworkDisconnectionReason = 15
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_DROPPED                    ENetworkDisconnectionReason = 16
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STEAM_OWNERSHIP                  ENetworkDisconnectionReason = 17
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SERVERINFO_OVERFLOW              ENetworkDisconnectionReason = 18
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_TICKMSG_OVERFLOW                 ENetworkDisconnectionReason = 19
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW          ENetworkDisconnectionReason = 20
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW             ENetworkDisconnectionReason = 21
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW              ENetworkDisconnectionReason = 22
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW               ENetworkDisconnectionReason = 23
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SNAPSHOTOVERFLOW                 ENetworkDisconnectionReason = 24
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SNAPSHOTERROR                    ENetworkDisconnectionReason = 25
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_RELIABLEOVERFLOW                 ENetworkDisconnectionReason = 26
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_BADDELTATICK                     ENetworkDisconnectionReason = 27
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_NOMORESPLITS                     ENetworkDisconnectionReason = 28
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_TIMEDOUT                         ENetworkDisconnectionReason = 29
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DISCONNECTED                     ENetworkDisconnectionReason = 30
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_LEAVINGSPLIT                     ENetworkDisconnectionReason = 31
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DIFFERENTCLASSTABLES             ENetworkDisconnectionReason = 32
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_BADRELAYPASSWORD                 ENetworkDisconnectionReason = 33
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_BADSPECTATORPASSWORD             ENetworkDisconnectionReason = 34
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_HLTVRESTRICTED                   ENetworkDisconnectionReason = 35
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_NOSPECTATORS                     ENetworkDisconnectionReason = 36
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_HLTVUNAVAILABLE                  ENetworkDisconnectionReason = 37
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_HLTVSTOP                         ENetworkDisconnectionReason = 38
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_KICKED                           ENetworkDisconnectionReason = 39
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_BANADDED                         ENetworkDisconnectionReason = 40
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_KICKBANADDED                     ENetworkDisconnectionReason = 41
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_HLTVDIRECT                       ENetworkDisconnectionReason = 42
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA           ENetworkDisconnectionReason = 43
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_PURESERVER_MISMATCH              ENetworkDisconnectionReason = 44
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_USERCMD                          ENetworkDisconnectionReason = 45
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_REJECTED_BY_GAME                 ENetworkDisconnectionReason = 46
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR              ENetworkDisconnectionReason = 47
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR            ENetworkDisconnectionReason = 48
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_BAD_SERVER_PASSWORD              ENetworkDisconnectionReason = 49
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION       ENetworkDisconnectionReason = 50
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_CONNECTION_FAILURE               ENetworkDisconnectionReason = 51
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS           ENetworkDisconnectionReason = 52
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_RECONNECTION                     ENetworkDisconnectionReason = 53
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_CONNECTION_CLOSING               ENetworkDisconnectionReason = 54
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_NO_GOTV_RELAYS_AVAILABLE         ENetworkDisconnectionReason = 55
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SESSION_MIGRATED                 ENetworkDisconnectionReason = 56
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_VERYLARGETRANSFEROVERFLOW        ENetworkDisconnectionReason = 57
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_SENDNETOVERFLOW                  ENetworkDisconnectionReason = 58
	ENetworkDisconnectionReason_NETWORK_DISCONNECT_PLAYER_REMOVED_FROM_HOST_SESSION ENetworkDisconnectionReason = 59
)

// Enum value maps for ENetworkDisconnectionReason.
var (
	ENetworkDisconnectionReason_name = map[int32]string{
		0:  "NETWORK_DISCONNECT_INVALID",
		1:  "NETWORK_DISCONNECT_SHUTDOWN",
		2:  "NETWORK_DISCONNECT_DISCONNECT_BY_USER",
		3:  "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER",
		4:  "NETWORK_DISCONNECT_LOST",
		5:  "NETWORK_DISCONNECT_OVERFLOW",
		6:  "NETWORK_DISCONNECT_STEAM_BANNED",
		7:  "NETWORK_DISCONNECT_STEAM_INUSE",
		8:  "NETWORK_DISCONNECT_STEAM_TICKET",
		9:  "NETWORK_DISCONNECT_STEAM_LOGON",
		10: "NETWORK_DISCONNECT_STEAM_AUTHCANCELLED",
		11: "NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED",
		12: "NETWORK_DISCONNECT_STEAM_AUTHINVALID",
		13: "NETWORK_DISCONNECT_STEAM_VACBANSTATE",
		14: "NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE",
		15: "NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT",
		16: "NETWORK_DISCONNECT_STEAM_DROPPED",
		17: "NETWORK_DISCONNECT_STEAM_OWNERSHIP",
		18: "NETWORK_DISCONNECT_SERVERINFO_OVERFLOW",
		19: "NETWORK_DISCONNECT_TICKMSG_OVERFLOW",
		20: "NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW",
		21: "NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW",
		22: "NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW",
		23: "NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW",
		24: "NETWORK_DISCONNECT_SNAPSHOTOVERFLOW",
		25: "NETWORK_DISCONNECT_SNAPSHOTERROR",
		26: "NETWORK_DISCONNECT_RELIABLEOVERFLOW",
		27: "NETWORK_DISCONNECT_BADDELTATICK",
		28: "NETWORK_DISCONNECT_NOMORESPLITS",
		29: "NETWORK_DISCONNECT_TIMEDOUT",
		30: "NETWORK_DISCONNECT_DISCONNECTED",
		31: "NETWORK_DISCONNECT_LEAVINGSPLIT",
		32: "NETWORK_DISCONNECT_DIFFERENTCLASSTABLES",
		33: "NETWORK_DISCONNECT_BADRELAYPASSWORD",
		34: "NETWORK_DISCONNECT_BADSPECTATORPASSWORD",
		35: "NETWORK_DISCONNECT_HLTVRESTRICTED",
		36: "NETWORK_DISCONNECT_NOSPECTATORS",
		37: "NETWORK_DISCONNECT_HLTVUNAVAILABLE",
		38: "NETWORK_DISCONNECT_HLTVSTOP",
		39: "NETWORK_DISCONNECT_KICKED",
		40: "NETWORK_DISCONNECT_BANADDED",
		41: "NETWORK_DISCONNECT_KICKBANADDED",
		42: "NETWORK_DISCONNECT_HLTVDIRECT",
		43: "NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA",
		44: "NETWORK_DISCONNECT_PURESERVER_MISMATCH",
		45: "NETWORK_DISCONNECT_USERCMD",
		46: "NETWORK_DISCONNECT_REJECTED_BY_GAME",
		47: "NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR",
		48: "NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR",
		49: "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD",
		50: "NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION",
		51: "NETWORK_DISCONNECT_CONNECTION_FAILURE",
		52: "NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS",
		53: "NETWORK_DISCONNECT_RECONNECTION",
		54: "NETWORK_DISCONNECT_CONNECTION_CLOSING",
		55: "NETWORK_DISCONNECT_NO_GOTV_RELAYS_AVAILABLE",
		56: "NETWORK_DISCONNECT_SESSION_MIGRATED",
		57: "NETWORK_DISCONNECT_VERYLARGETRANSFEROVERFLOW",
		58: "NETWORK_DISCONNECT_SENDNETOVERFLOW",
		59: "NETWORK_DISCONNECT_PLAYER_REMOVED_FROM_HOST_SESSION",
	}
	ENetworkDisconnectionReason_value = map[string]int32{
		"NETWORK_DISCONNECT_INVALID":                          0,
		"NETWORK_DISCONNECT_SHUTDOWN":                         1,
		"NETWORK_DISCONNECT_DISCONNECT_BY_USER":               2,
		"NETWORK_DISCONNECT_DISCONNECT_BY_SERVER":             3,
		"NETWORK_DISCONNECT_LOST":                             4,
		"NETWORK_DISCONNECT_OVERFLOW":                         5,
		"NETWORK_DISCONNECT_STEAM_BANNED":                     6,
		"NETWORK_DISCONNECT_STEAM_INUSE":                      7,
		"NETWORK_DISCONNECT_STEAM_TICKET":                     8,
		"NETWORK_DISCONNECT_STEAM_LOGON":                      9,
		"NETWORK_DISCONNECT_STEAM_AUTHCANCELLED":              10,
		"NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED":            11,
		"NETWORK_DISCONNECT_STEAM_AUTHINVALID":                12,
		"NETWORK_DISCONNECT_STEAM_VACBANSTATE":                13,
		"NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE":        14,
		"NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT":         15,
		"NETWORK_DISCONNECT_STEAM_DROPPED":                    16,
		"NETWORK_DISCONNECT_STEAM_OWNERSHIP":                  17,
		"NETWORK_DISCONNECT_SERVERINFO_OVERFLOW":              18,
		"NETWORK_DISCONNECT_TICKMSG_OVERFLOW":                 19,
		"NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW":          20,
		"NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW":             21,
		"NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW":              22,
		"NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW":               23,
		"NETWORK_DISCONNECT_SNAPSHOTOVERFLOW":                 24,
		"NETWORK_DISCONNECT_SNAPSHOTERROR":                    25,
		"NETWORK_DISCONNECT_RELIABLEOVERFLOW":                 26,
		"NETWORK_DISCONNECT_BADDELTATICK":                     27,
		"NETWORK_DISCONNECT_NOMORESPLITS":                     28,
		"NETWORK_DISCONNECT_TIMEDOUT":                         29,
		"NETWORK_DISCONNECT_DISCONNECTED":                     30,
		"NETWORK_DISCONNECT_LEAVINGSPLIT":                     31,
		"NETWORK_DISCONNECT_DIFFERENTCLASSTABLES":             32,
		"NETWORK_DISCONNECT_BADRELAYPASSWORD":                 33,
		"NETWORK_DISCONNECT_BADSPECTATORPASSWORD":             34,
		"NETWORK_DISCONNECT_HLTVRESTRICTED":                   35,
		"NETWORK_DISCONNECT_NOSPECTATORS":                     36,
		"NETWORK_DISCONNECT_HLTVUNAVAILABLE":                  37,
		"NETWORK_DISCONNECT_HLTVSTOP":                         38,
		"NETWORK_DISCONNECT_KICKED":                           39,
		"NETWORK_DISCONNECT_BANADDED":                         40,
		"NETWORK_DISCONNECT_KICKBANADDED":                     41,
		"NETWORK_DISCONNECT_HLTVDIRECT":                       42,
		"NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA":           43,
		"NETWORK_DISCONNECT_PURESERVER_MISMATCH":              44,
		"NETWORK_DISCONNECT_USERCMD":                          45,
		"NETWORK_DISCONNECT_REJECTED_BY_GAME":                 46,
		"NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR":              47,
		"NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR":            48,
		"NETWORK_DISCONNECT_BAD_SERVER_PASSWORD":              49,
		"NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION":       50,
		"NETWORK_DISCONNECT_CONNECTION_FAILURE":               51,
		"NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS":           52,
		"NETWORK_DISCONNECT_RECONNECTION":                     53,
		"NETWORK_DISCONNECT_CONNECTION_CLOSING":               54,
		"NETWORK_DISCONNECT_NO_GOTV_RELAYS_AVAILABLE":         55,
		"NETWORK_DISCONNECT_SESSION_MIGRATED":                 56,
		"NETWORK_DISCONNECT_VERYLARGETRANSFEROVERFLOW":        57,
		"NETWORK_DISCONNECT_SENDNETOVERFLOW":                  58,
		"NETWORK_DISCONNECT_PLAYER_REMOVED_FROM_HOST_SESSION": 59,
	}
)

func (x ENetworkDisconnectionReason) Enum() *ENetworkDisconnectionReason {
	p := new(ENetworkDisconnectionReason)
	*p = x
	return p
}

func (x ENetworkDisconnectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENetworkDisconnectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_network_connection_proto_enumTypes[0].Descriptor()
}

func (ENetworkDisconnectionReason) Type() protoreflect.EnumType {
	return &file_network_connection_proto_enumTypes[0]
}

func (x ENetworkDisconnectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ENetworkDisconnectionReason) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ENetworkDisconnectionReason(num)
	return nil
}

// Deprecated: Use ENetworkDisconnectionReason.Descriptor instead.
func (ENetworkDisconnectionReason) EnumDescriptor() ([]byte, []int) {
	return file_network_connection_proto_rawDescGZIP(), []int{0}
}

var file_network_connection_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor_proto.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50500,
		Name:          "network_connection_token",
		Tag:           "bytes,50500,opt,name=network_connection_token",
		Filename:      "network_connection.proto",
	},
}

// Extension fields to descriptor_proto.EnumValueOptions.
var (
	// optional string network_connection_token = 50500;
	E_NetworkConnectionToken = &file_network_connection_proto_extTypes[0]
)

var File_network_connection_proto protoreflect.FileDescriptor

const file_network_connection_proto_rawDesc = "" +
	"\n" +
	"\x18network_connection.proto\x1a google.golang.org/protobuf/types/descriptorpb*\x8c%\n" +
	"\x1bENetworkDisconnectionReason\x12\x1e\n" +
	"\x1aNETWORK_DISCONNECT_INVALID\x10\x00\x12\x1f\n" +
	"\x1bNETWORK_DISCONNECT_SHUTDOWN\x10\x01\x12F\n" +
	"%NETWORK_DISCONNECT_DISCONNECT_BY_USER\x10\x02\x1a\x1b\xa2\xd4\x18\x17#GameUI_Disconnect_User\x12J\n" +
	"'NETWORK_DISCONNECT_DISCONNECT_BY_SERVER\x10\x03\x1a\x1d\xa2\xd4\x18\x19#GameUI_Disconnect_Server\x12B\n" +
	"\x17NETWORK_DISCONNECT_LOST\x10\x04\x1a%\xa2\xd4\x18!#GameUI_Disconnect_ConnectionLost\x12J\n" +
	"\x1bNETWORK_DISCONNECT_OVERFLOW\x10\x05\x1a)\xa2\xd4\x18%#GameUI_Disconnect_ConnectionOverflow\x12I\n" +
	"\x1fNETWORK_DISCONNECT_STEAM_BANNED\x10\x06\x1a$\xa2\xd4\x18 #GameUI_Disconnect_SteamIDBanned\x12G\n" +
	"\x1eNETWORK_DISCONNECT_STEAM_INUSE\x10\a\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_SteamIDInUse\x12G\n" +
	"\x1fNETWORK_DISCONNECT_STEAM_TICKET\x10\b\x1a\"\xa2\xd4\x18\x1e#GameUI_Disconnect_SteamTicket\x12E\n" +
	"\x1eNETWORK_DISCONNECT_STEAM_LOGON\x10\t\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12M\n" +
	"&NETWORK_DISCONNECT_STEAM_AUTHCANCELLED\x10\n" +
	"\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12O\n" +
	"(NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED\x10\v\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12K\n" +
	"$NETWORK_DISCONNECT_STEAM_AUTHINVALID\x10\f\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamLogon\x12I\n" +
	"$NETWORK_DISCONNECT_STEAM_VACBANSTATE\x10\r\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_SteamVAC\x12S\n" +
	",NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE\x10\x0e\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_SteamInUse\x12T\n" +
	"+NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT\x10\x0f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_SteamTimeOut\x12I\n" +
	" NETWORK_DISCONNECT_STEAM_DROPPED\x10\x10\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_SteamDropped\x12M\n" +
	"\"NETWORK_DISCONNECT_STEAM_OWNERSHIP\x10\x11\x1a%\xa2\xd4\x18!#GameUI_Disconnect_SteamOwnership\x12U\n" +
	"&NETWORK_DISCONNECT_SERVERINFO_OVERFLOW\x10\x12\x1a)\xa2\xd4\x18%#GameUI_Disconnect_ServerInfoOverflow\x12K\n" +
	"#NETWORK_DISCONNECT_TICKMSG_OVERFLOW\x10\x13\x1a\"\xa2\xd4\x18\x1e#GameUI_Disconnect_TickMessage\x12Y\n" +
	"*NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW\x10\x14\x1a)\xa2\xd4\x18%#GameUI_Disconnect_StringTableMessage\x12S\n" +
	"'NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW\x10\x15\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_DeltaEntMessage\x12Q\n" +
	"&NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW\x10\x16\x1a%\xa2\xd4\x18!#GameUI_Disconnect_TempEntMessage\x12O\n" +
	"%NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW\x10\x17\x1a$\xa2\xd4\x18 #GameUI_Disconnect_SoundsMessage\x12P\n" +
	"#NETWORK_DISCONNECT_SNAPSHOTOVERFLOW\x10\x18\x1a'\xa2\xd4\x18##GameUI_Disconnect_SnapshotOverflow\x12J\n" +
	" NETWORK_DISCONNECT_SNAPSHOTERROR\x10\x19\x1a$\xa2\xd4\x18 #GameUI_Disconnect_SnapshotError\x12P\n" +
	"#NETWORK_DISCONNECT_RELIABLEOVERFLOW\x10\x1a\x1a'\xa2\xd4\x18##GameUI_Disconnect_ReliableOverflow\x12N\n" +
	"\x1fNETWORK_DISCONNECT_BADDELTATICK\x10\x1b\x1a)\xa2\xd4\x18%#GameUI_Disconnect_BadClientDeltaTick\x12H\n" +
	"\x1fNETWORK_DISCONNECT_NOMORESPLITS\x10\x1c\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_NoMoreSplits\x12@\n" +
	"\x1bNETWORK_DISCONNECT_TIMEDOUT\x10\x1d\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_TimedOut\x12H\n" +
	"\x1fNETWORK_DISCONNECT_DISCONNECTED\x10\x1e\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_Disconnected\x12H\n" +
	"\x1fNETWORK_DISCONNECT_LEAVINGSPLIT\x10\x1f\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_LeavingSplit\x12X\n" +
	"'NETWORK_DISCONNECT_DIFFERENTCLASSTABLES\x10 \x1a+\xa2\xd4\x18'#GameUI_Disconnect_DifferentClassTables\x12P\n" +
	"#NETWORK_DISCONNECT_BADRELAYPASSWORD\x10!\x1a'\xa2\xd4\x18##GameUI_Disconnect_BadRelayPassword\x12X\n" +
	"'NETWORK_DISCONNECT_BADSPECTATORPASSWORD\x10\"\x1a+\xa2\xd4\x18'#GameUI_Disconnect_BadSpectatorPassword\x12L\n" +
	"!NETWORK_DISCONNECT_HLTVRESTRICTED\x10#\x1a%\xa2\xd4\x18!#GameUI_Disconnect_HLTVRestricted\x12H\n" +
	"\x1fNETWORK_DISCONNECT_NOSPECTATORS\x10$\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_NoSpectators\x12N\n" +
	"\"NETWORK_DISCONNECT_HLTVUNAVAILABLE\x10%\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_HLTVUnavailable\x12@\n" +
	"\x1bNETWORK_DISCONNECT_HLTVSTOP\x10&\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_HLTVStop\x12<\n" +
	"\x19NETWORK_DISCONNECT_KICKED\x10'\x1a\x1d\xa2\xd4\x18\x19#GameUI_Disconnect_Kicked\x12@\n" +
	"\x1bNETWORK_DISCONNECT_BANADDED\x10(\x1a\x1f\xa2\xd4\x18\x1b#GameUI_Disconnect_BanAdded\x12H\n" +
	"\x1fNETWORK_DISCONNECT_KICKBANADDED\x10)\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_KickBanAdded\x12D\n" +
	"\x1dNETWORK_DISCONNECT_HLTVDIRECT\x10*\x1a!\xa2\xd4\x18\x1d#GameUI_Disconnect_HLTVDirect\x12\\\n" +
	")NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA\x10+\x1a-\xa2\xd4\x18)#GameUI_Disconnect_PureServer_ClientExtra\x12V\n" +
	"&NETWORK_DISCONNECT_PURESERVER_MISMATCH\x10,\x1a*\xa2\xd4\x18&#GameUI_Disconnect_PureServer_Mismatch\x12>\n" +
	"\x1aNETWORK_DISCONNECT_USERCMD\x10-\x1a\x1e\xa2\xd4\x18\x1a#GameUI_Disconnect_UserCmd\x12N\n" +
	"#NETWORK_DISCONNECT_REJECTED_BY_GAME\x10.\x1a%\xa2\xd4\x18!#GameUI_Disconnect_RejectedByGame\x12T\n" +
	"&NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR\x10/\x1a(\xa2\xd4\x18$#GameUI_Disconnect_MessageParseError\x12X\n" +
	"(NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR\x100\x1a*\xa2\xd4\x18&#GameUI_Disconnect_InvalidMessageError\x12T\n" +
	"&NETWORK_DISCONNECT_BAD_SERVER_PASSWORD\x101\x1a(\xa2\xd4\x18$#GameUI_Disconnect_BadServerPassword\x12b\n" +
	"-NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION\x102\x1a/\xa2\xd4\x18+#GameUI_Disconnect_DirectConnectReservation\x12S\n" +
	"%NETWORK_DISCONNECT_CONNECTION_FAILURE\x103\x1a(\xa2\xd4\x18$#GameUI_Disconnect_ConnectionFailure\x12Y\n" +
	")NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS\x104\x1a*\xa2\xd4\x18&#GameUI_Disconnect_NoPeerGroupHandlers\x12H\n" +
	"\x1fNETWORK_DISCONNECT_RECONNECTION\x105\x1a#\xa2\xd4\x18\x1f#GameUI_Disconnect_Reconnection\x12S\n" +
	"%NETWORK_DISCONNECT_CONNECTION_CLOSING\x106\x1a(\xa2\xd4\x18$#GameUI_Disconnect_ConnectionClosing\x12]\n" +
	"+NETWORK_DISCONNECT_NO_GOTV_RELAYS_AVAILABLE\x107\x1a,\xa2\xd4\x18(#GameUI_Disconnect_NoGOTVRelaysAvailable\x12O\n" +
	"#NETWORK_DISCONNECT_SESSION_MIGRATED\x108\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_SessionMigrated\x12b\n" +
	",NETWORK_DISCONNECT_VERYLARGETRANSFEROVERFLOW\x109\x1a0\xa2\xd4\x18,#GameUI_Disconnect_VeryLargeTransferOverflow\x12N\n" +
	"\"NETWORK_DISCONNECT_SENDNETOVERFLOW\x10:\x1a&\xa2\xd4\x18\"#GameUI_Disconnect_SendNetOverflow\x12l\n" +
	"3NETWORK_DISCONNECT_PLAYER_REMOVED_FROM_HOST_SESSION\x10;\x1a3\xa2\xd4\x18/#GameUI_Disconnect_PlayerRemovedFromHostSession:]\n" +
	"\x18network_connection_token\x12!.google.protobuf.EnumValueOptions\x18Ċ\x03 \x01(\tR\x16networkConnectionTokenB\x03\x80\x01\x00"

var (
	file_network_connection_proto_rawDescOnce sync.Once
	file_network_connection_proto_rawDescData []byte
)

func file_network_connection_proto_rawDescGZIP() []byte {
	file_network_connection_proto_rawDescOnce.Do(func() {
		file_network_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_connection_proto_rawDesc), len(file_network_connection_proto_rawDesc)))
	})
	return file_network_connection_proto_rawDescData
}

var file_network_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_connection_proto_goTypes = []any{
	(ENetworkDisconnectionReason)(0),          // 0: ENetworkDisconnectionReason
	(*descriptor_proto.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_network_connection_proto_depIdxs = []int32{
	1, // 0: network_connection_token:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_connection_proto_init() }
func file_network_connection_proto_init() {
	if File_network_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_connection_proto_rawDesc), len(file_network_connection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_network_connection_proto_goTypes,
		DependencyIndexes: file_network_connection_proto_depIdxs,
		EnumInfos:         file_network_connection_proto_enumTypes,
		ExtensionInfos:    file_network_connection_proto_extTypes,
	}.Build()
	File_network_connection_proto = out.File
	file_network_connection_proto_goTypes = nil
	file_network_connection_proto_depIdxs = nil
}
