// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gcsystemmsgs.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EGCSystemMsg int32

const (
	EGCSystemMsg_k_EGCMsgInvalid                                  EGCSystemMsg = 0
	EGCSystemMsg_k_EGCMsgMulti                                    EGCSystemMsg = 1
	EGCSystemMsg_k_EGCMsgGenericReply                             EGCSystemMsg = 10
	EGCSystemMsg_k_EGCMsgSystemBase                               EGCSystemMsg = 50
	EGCSystemMsg_k_EGCMsgAchievementAwarded                       EGCSystemMsg = 51
	EGCSystemMsg_k_EGCMsgConCommand                               EGCSystemMsg = 52
	EGCSystemMsg_k_EGCMsgStartPlaying                             EGCSystemMsg = 53
	EGCSystemMsg_k_EGCMsgStopPlaying                              EGCSystemMsg = 54
	EGCSystemMsg_k_EGCMsgStartGameserver                          EGCSystemMsg = 55
	EGCSystemMsg_k_EGCMsgStopGameserver                           EGCSystemMsg = 56
	EGCSystemMsg_k_EGCMsgWGRequest                                EGCSystemMsg = 57
	EGCSystemMsg_k_EGCMsgWGResponse                               EGCSystemMsg = 58
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchema                   EGCSystemMsg = 59
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchemaResponse           EGCSystemMsg = 60
	EGCSystemMsg_k_EGCMsgGetUserStatsDEPRECATED                   EGCSystemMsg = 61
	EGCSystemMsg_k_EGCMsgGetUserStatsResponse                     EGCSystemMsg = 62
	EGCSystemMsg_k_EGCMsgAppInfoUpdated                           EGCSystemMsg = 63
	EGCSystemMsg_k_EGCMsgValidateSession                          EGCSystemMsg = 64
	EGCSystemMsg_k_EGCMsgValidateSessionResponse                  EGCSystemMsg = 65
	EGCSystemMsg_k_EGCMsgLookupAccountFromInput                   EGCSystemMsg = 66
	EGCSystemMsg_k_EGCMsgSendHTTPRequest                          EGCSystemMsg = 67
	EGCSystemMsg_k_EGCMsgSendHTTPRequestResponse                  EGCSystemMsg = 68
	EGCSystemMsg_k_EGCMsgPreTestSetup                             EGCSystemMsg = 69
	EGCSystemMsg_k_EGCMsgRecordSupportAction                      EGCSystemMsg = 70
	EGCSystemMsg_k_EGCMsgGetAccountDetails_DEPRECATED             EGCSystemMsg = 71
	EGCSystemMsg_k_EGCMsgReceiveInterAppMessage                   EGCSystemMsg = 73
	EGCSystemMsg_k_EGCMsgFindAccounts                             EGCSystemMsg = 74
	EGCSystemMsg_k_EGCMsgPostAlert                                EGCSystemMsg = 75
	EGCSystemMsg_k_EGCMsgGetLicenses                              EGCSystemMsg = 76
	EGCSystemMsg_k_EGCMsgGetUserStats                             EGCSystemMsg = 77
	EGCSystemMsg_k_EGCMsgGetCommands                              EGCSystemMsg = 78
	EGCSystemMsg_k_EGCMsgGetCommandsResponse                      EGCSystemMsg = 79
	EGCSystemMsg_k_EGCMsgAddFreeLicense                           EGCSystemMsg = 80
	EGCSystemMsg_k_EGCMsgAddFreeLicenseResponse                   EGCSystemMsg = 81
	EGCSystemMsg_k_EGCMsgGetIPLocation                            EGCSystemMsg = 82
	EGCSystemMsg_k_EGCMsgGetIPLocationResponse                    EGCSystemMsg = 83
	EGCSystemMsg_k_EGCMsgSystemStatsSchema                        EGCSystemMsg = 84
	EGCSystemMsg_k_EGCMsgGetSystemStats                           EGCSystemMsg = 85
	EGCSystemMsg_k_EGCMsgGetSystemStatsResponse                   EGCSystemMsg = 86
	EGCSystemMsg_k_EGCMsgSendEmail                                EGCSystemMsg = 87
	EGCSystemMsg_k_EGCMsgSendEmailResponse                        EGCSystemMsg = 88
	EGCSystemMsg_k_EGCMsgGetEmailTemplate                         EGCSystemMsg = 89
	EGCSystemMsg_k_EGCMsgGetEmailTemplateResponse                 EGCSystemMsg = 90
	EGCSystemMsg_k_EGCMsgGrantGuestPass                           EGCSystemMsg = 91
	EGCSystemMsg_k_EGCMsgGrantGuestPassResponse                   EGCSystemMsg = 92
	EGCSystemMsg_k_EGCMsgGetAccountDetails                        EGCSystemMsg = 93
	EGCSystemMsg_k_EGCMsgGetAccountDetailsResponse                EGCSystemMsg = 94
	EGCSystemMsg_k_EGCMsgGetPersonaNames                          EGCSystemMsg = 95
	EGCSystemMsg_k_EGCMsgGetPersonaNamesResponse                  EGCSystemMsg = 96
	EGCSystemMsg_k_EGCMsgMultiplexMsg                             EGCSystemMsg = 97
	EGCSystemMsg_k_EGCMsgMultiplexMsgResponse                     EGCSystemMsg = 98
	EGCSystemMsg_k_EGCMsgWebAPIRegisterInterfaces                 EGCSystemMsg = 101
	EGCSystemMsg_k_EGCMsgWebAPIJobRequest                         EGCSystemMsg = 102
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestHttpResponse             EGCSystemMsg = 104
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestForwardResponse          EGCSystemMsg = 105
	EGCSystemMsg_k_EGCMsgMemCachedGet                             EGCSystemMsg = 200
	EGCSystemMsg_k_EGCMsgMemCachedGetResponse                     EGCSystemMsg = 201
	EGCSystemMsg_k_EGCMsgMemCachedSet                             EGCSystemMsg = 202
	EGCSystemMsg_k_EGCMsgMemCachedDelete                          EGCSystemMsg = 203
	EGCSystemMsg_k_EGCMsgMemCachedStats                           EGCSystemMsg = 204
	EGCSystemMsg_k_EGCMsgMemCachedStatsResponse                   EGCSystemMsg = 205
	EGCSystemMsg_k_EGCMsgMasterSetDirectory                       EGCSystemMsg = 220
	EGCSystemMsg_k_EGCMsgMasterSetDirectoryResponse               EGCSystemMsg = 221
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRouting                   EGCSystemMsg = 222
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRoutingResponse           EGCSystemMsg = 223
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRouting                EGCSystemMsg = 224
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRoutingResponse        EGCSystemMsg = 225
	EGCSystemMsg_k_EGCMsgSetOptions                               EGCSystemMsg = 226
	EGCSystemMsg_k_EGCMsgSetOptionsResponse                       EGCSystemMsg = 227
	EGCSystemMsg_k_EGCMsgSystemBase2                              EGCSystemMsg = 500
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatus                   EGCSystemMsg = 501
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatusResponse           EGCSystemMsg = 502
	EGCSystemMsg_k_EGCMsgUpdateSession                            EGCSystemMsg = 503
	EGCSystemMsg_k_EGCMsgGCAccountVacStatusChange                 EGCSystemMsg = 504
	EGCSystemMsg_k_EGCMsgCheckFriendship                          EGCSystemMsg = 505
	EGCSystemMsg_k_EGCMsgCheckFriendshipResponse                  EGCSystemMsg = 506
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLink                    EGCSystemMsg = 507
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLinkResponse            EGCSystemMsg = 508
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxns                       EGCSystemMsg = 512
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxnsResponse               EGCSystemMsg = 513
	EGCSystemMsg_k_EGCMsgVacVerificationChange                    EGCSystemMsg = 518
	EGCSystemMsg_k_EGCMsgAccountPhoneNumberChange                 EGCSystemMsg = 519
	EGCSystemMsg_k_EGCMsgInviteUserToLobby                        EGCSystemMsg = 523
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesRequest     EGCSystemMsg = 524
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesResponse    EGCSystemMsg = 525
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesRequest        EGCSystemMsg = 526
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesResponse       EGCSystemMsg = 527
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesRequest  EGCSystemMsg = 528
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesResponse EGCSystemMsg = 529
	EGCSystemMsg_k_EGCMsgRecurringSubscriptionStatusChange        EGCSystemMsg = 530
	EGCSystemMsg_k_EGCMsgDirectServiceMethod                      EGCSystemMsg = 531
	EGCSystemMsg_k_EGCMsgDirectServiceMethodResponse              EGCSystemMsg = 532
)

// Enum value maps for EGCSystemMsg.
var (
	EGCSystemMsg_name = map[int32]string{
		0:   "k_EGCMsgInvalid",
		1:   "k_EGCMsgMulti",
		10:  "k_EGCMsgGenericReply",
		50:  "k_EGCMsgSystemBase",
		51:  "k_EGCMsgAchievementAwarded",
		52:  "k_EGCMsgConCommand",
		53:  "k_EGCMsgStartPlaying",
		54:  "k_EGCMsgStopPlaying",
		55:  "k_EGCMsgStartGameserver",
		56:  "k_EGCMsgStopGameserver",
		57:  "k_EGCMsgWGRequest",
		58:  "k_EGCMsgWGResponse",
		59:  "k_EGCMsgGetUserGameStatsSchema",
		60:  "k_EGCMsgGetUserGameStatsSchemaResponse",
		61:  "k_EGCMsgGetUserStatsDEPRECATED",
		62:  "k_EGCMsgGetUserStatsResponse",
		63:  "k_EGCMsgAppInfoUpdated",
		64:  "k_EGCMsgValidateSession",
		65:  "k_EGCMsgValidateSessionResponse",
		66:  "k_EGCMsgLookupAccountFromInput",
		67:  "k_EGCMsgSendHTTPRequest",
		68:  "k_EGCMsgSendHTTPRequestResponse",
		69:  "k_EGCMsgPreTestSetup",
		70:  "k_EGCMsgRecordSupportAction",
		71:  "k_EGCMsgGetAccountDetails_DEPRECATED",
		73:  "k_EGCMsgReceiveInterAppMessage",
		74:  "k_EGCMsgFindAccounts",
		75:  "k_EGCMsgPostAlert",
		76:  "k_EGCMsgGetLicenses",
		77:  "k_EGCMsgGetUserStats",
		78:  "k_EGCMsgGetCommands",
		79:  "k_EGCMsgGetCommandsResponse",
		80:  "k_EGCMsgAddFreeLicense",
		81:  "k_EGCMsgAddFreeLicenseResponse",
		82:  "k_EGCMsgGetIPLocation",
		83:  "k_EGCMsgGetIPLocationResponse",
		84:  "k_EGCMsgSystemStatsSchema",
		85:  "k_EGCMsgGetSystemStats",
		86:  "k_EGCMsgGetSystemStatsResponse",
		87:  "k_EGCMsgSendEmail",
		88:  "k_EGCMsgSendEmailResponse",
		89:  "k_EGCMsgGetEmailTemplate",
		90:  "k_EGCMsgGetEmailTemplateResponse",
		91:  "k_EGCMsgGrantGuestPass",
		92:  "k_EGCMsgGrantGuestPassResponse",
		93:  "k_EGCMsgGetAccountDetails",
		94:  "k_EGCMsgGetAccountDetailsResponse",
		95:  "k_EGCMsgGetPersonaNames",
		96:  "k_EGCMsgGetPersonaNamesResponse",
		97:  "k_EGCMsgMultiplexMsg",
		98:  "k_EGCMsgMultiplexMsgResponse",
		101: "k_EGCMsgWebAPIRegisterInterfaces",
		102: "k_EGCMsgWebAPIJobRequest",
		104: "k_EGCMsgWebAPIJobRequestHttpResponse",
		105: "k_EGCMsgWebAPIJobRequestForwardResponse",
		200: "k_EGCMsgMemCachedGet",
		201: "k_EGCMsgMemCachedGetResponse",
		202: "k_EGCMsgMemCachedSet",
		203: "k_EGCMsgMemCachedDelete",
		204: "k_EGCMsgMemCachedStats",
		205: "k_EGCMsgMemCachedStatsResponse",
		220: "k_EGCMsgMasterSetDirectory",
		221: "k_EGCMsgMasterSetDirectoryResponse",
		222: "k_EGCMsgMasterSetWebAPIRouting",
		223: "k_EGCMsgMasterSetWebAPIRoutingResponse",
		224: "k_EGCMsgMasterSetClientMsgRouting",
		225: "k_EGCMsgMasterSetClientMsgRoutingResponse",
		226: "k_EGCMsgSetOptions",
		227: "k_EGCMsgSetOptionsResponse",
		500: "k_EGCMsgSystemBase2",
		501: "k_EGCMsgGetPurchaseTrustStatus",
		502: "k_EGCMsgGetPurchaseTrustStatusResponse",
		503: "k_EGCMsgUpdateSession",
		504: "k_EGCMsgGCAccountVacStatusChange",
		505: "k_EGCMsgCheckFriendship",
		506: "k_EGCMsgCheckFriendshipResponse",
		507: "k_EGCMsgGetPartnerAccountLink",
		508: "k_EGCMsgGetPartnerAccountLinkResponse",
		512: "k_EGCMsgDPPartnerMicroTxns",
		513: "k_EGCMsgDPPartnerMicroTxnsResponse",
		518: "k_EGCMsgVacVerificationChange",
		519: "k_EGCMsgAccountPhoneNumberChange",
		523: "k_EGCMsgInviteUserToLobby",
		524: "k_EGCMsgGetGamePersonalDataCategoriesRequest",
		525: "k_EGCMsgGetGamePersonalDataCategoriesResponse",
		526: "k_EGCMsgGetGamePersonalDataEntriesRequest",
		527: "k_EGCMsgGetGamePersonalDataEntriesResponse",
		528: "k_EGCMsgTerminateGamePersonalDataEntriesRequest",
		529: "k_EGCMsgTerminateGamePersonalDataEntriesResponse",
		530: "k_EGCMsgRecurringSubscriptionStatusChange",
		531: "k_EGCMsgDirectServiceMethod",
		532: "k_EGCMsgDirectServiceMethodResponse",
	}
	EGCSystemMsg_value = map[string]int32{
		"k_EGCMsgInvalid":                                  0,
		"k_EGCMsgMulti":                                    1,
		"k_EGCMsgGenericReply":                             10,
		"k_EGCMsgSystemBase":                               50,
		"k_EGCMsgAchievementAwarded":                       51,
		"k_EGCMsgConCommand":                               52,
		"k_EGCMsgStartPlaying":                             53,
		"k_EGCMsgStopPlaying":                              54,
		"k_EGCMsgStartGameserver":                          55,
		"k_EGCMsgStopGameserver":                           56,
		"k_EGCMsgWGRequest":                                57,
		"k_EGCMsgWGResponse":                               58,
		"k_EGCMsgGetUserGameStatsSchema":                   59,
		"k_EGCMsgGetUserGameStatsSchemaResponse":           60,
		"k_EGCMsgGetUserStatsDEPRECATED":                   61,
		"k_EGCMsgGetUserStatsResponse":                     62,
		"k_EGCMsgAppInfoUpdated":                           63,
		"k_EGCMsgValidateSession":                          64,
		"k_EGCMsgValidateSessionResponse":                  65,
		"k_EGCMsgLookupAccountFromInput":                   66,
		"k_EGCMsgSendHTTPRequest":                          67,
		"k_EGCMsgSendHTTPRequestResponse":                  68,
		"k_EGCMsgPreTestSetup":                             69,
		"k_EGCMsgRecordSupportAction":                      70,
		"k_EGCMsgGetAccountDetails_DEPRECATED":             71,
		"k_EGCMsgReceiveInterAppMessage":                   73,
		"k_EGCMsgFindAccounts":                             74,
		"k_EGCMsgPostAlert":                                75,
		"k_EGCMsgGetLicenses":                              76,
		"k_EGCMsgGetUserStats":                             77,
		"k_EGCMsgGetCommands":                              78,
		"k_EGCMsgGetCommandsResponse":                      79,
		"k_EGCMsgAddFreeLicense":                           80,
		"k_EGCMsgAddFreeLicenseResponse":                   81,
		"k_EGCMsgGetIPLocation":                            82,
		"k_EGCMsgGetIPLocationResponse":                    83,
		"k_EGCMsgSystemStatsSchema":                        84,
		"k_EGCMsgGetSystemStats":                           85,
		"k_EGCMsgGetSystemStatsResponse":                   86,
		"k_EGCMsgSendEmail":                                87,
		"k_EGCMsgSendEmailResponse":                        88,
		"k_EGCMsgGetEmailTemplate":                         89,
		"k_EGCMsgGetEmailTemplateResponse":                 90,
		"k_EGCMsgGrantGuestPass":                           91,
		"k_EGCMsgGrantGuestPassResponse":                   92,
		"k_EGCMsgGetAccountDetails":                        93,
		"k_EGCMsgGetAccountDetailsResponse":                94,
		"k_EGCMsgGetPersonaNames":                          95,
		"k_EGCMsgGetPersonaNamesResponse":                  96,
		"k_EGCMsgMultiplexMsg":                             97,
		"k_EGCMsgMultiplexMsgResponse":                     98,
		"k_EGCMsgWebAPIRegisterInterfaces":                 101,
		"k_EGCMsgWebAPIJobRequest":                         102,
		"k_EGCMsgWebAPIJobRequestHttpResponse":             104,
		"k_EGCMsgWebAPIJobRequestForwardResponse":          105,
		"k_EGCMsgMemCachedGet":                             200,
		"k_EGCMsgMemCachedGetResponse":                     201,
		"k_EGCMsgMemCachedSet":                             202,
		"k_EGCMsgMemCachedDelete":                          203,
		"k_EGCMsgMemCachedStats":                           204,
		"k_EGCMsgMemCachedStatsResponse":                   205,
		"k_EGCMsgMasterSetDirectory":                       220,
		"k_EGCMsgMasterSetDirectoryResponse":               221,
		"k_EGCMsgMasterSetWebAPIRouting":                   222,
		"k_EGCMsgMasterSetWebAPIRoutingResponse":           223,
		"k_EGCMsgMasterSetClientMsgRouting":                224,
		"k_EGCMsgMasterSetClientMsgRoutingResponse":        225,
		"k_EGCMsgSetOptions":                               226,
		"k_EGCMsgSetOptionsResponse":                       227,
		"k_EGCMsgSystemBase2":                              500,
		"k_EGCMsgGetPurchaseTrustStatus":                   501,
		"k_EGCMsgGetPurchaseTrustStatusResponse":           502,
		"k_EGCMsgUpdateSession":                            503,
		"k_EGCMsgGCAccountVacStatusChange":                 504,
		"k_EGCMsgCheckFriendship":                          505,
		"k_EGCMsgCheckFriendshipResponse":                  506,
		"k_EGCMsgGetPartnerAccountLink":                    507,
		"k_EGCMsgGetPartnerAccountLinkResponse":            508,
		"k_EGCMsgDPPartnerMicroTxns":                       512,
		"k_EGCMsgDPPartnerMicroTxnsResponse":               513,
		"k_EGCMsgVacVerificationChange":                    518,
		"k_EGCMsgAccountPhoneNumberChange":                 519,
		"k_EGCMsgInviteUserToLobby":                        523,
		"k_EGCMsgGetGamePersonalDataCategoriesRequest":     524,
		"k_EGCMsgGetGamePersonalDataCategoriesResponse":    525,
		"k_EGCMsgGetGamePersonalDataEntriesRequest":        526,
		"k_EGCMsgGetGamePersonalDataEntriesResponse":       527,
		"k_EGCMsgTerminateGamePersonalDataEntriesRequest":  528,
		"k_EGCMsgTerminateGamePersonalDataEntriesResponse": 529,
		"k_EGCMsgRecurringSubscriptionStatusChange":        530,
		"k_EGCMsgDirectServiceMethod":                      531,
		"k_EGCMsgDirectServiceMethodResponse":              532,
	}
)

func (x EGCSystemMsg) Enum() *EGCSystemMsg {
	p := new(EGCSystemMsg)
	*p = x
	return p
}

func (x EGCSystemMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGCSystemMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[0].Descriptor()
}

func (EGCSystemMsg) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[0]
}

func (x EGCSystemMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EGCSystemMsg) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EGCSystemMsg(num)
	return nil
}

// Deprecated: Use EGCSystemMsg.Descriptor instead.
func (EGCSystemMsg) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{0}
}

type ESOMsg int32

const (
	ESOMsg_k_ESOMsg_Create                   ESOMsg = 21
	ESOMsg_k_ESOMsg_Update                   ESOMsg = 22
	ESOMsg_k_ESOMsg_Destroy                  ESOMsg = 23
	ESOMsg_k_ESOMsg_CacheSubscribed          ESOMsg = 24
	ESOMsg_k_ESOMsg_CacheUnsubscribed        ESOMsg = 25
	ESOMsg_k_ESOMsg_UpdateMultiple           ESOMsg = 26
	ESOMsg_k_ESOMsg_CacheSubscriptionCheck   ESOMsg = 27
	ESOMsg_k_ESOMsg_CacheSubscriptionRefresh ESOMsg = 28
)

// Enum value maps for ESOMsg.
var (
	ESOMsg_name = map[int32]string{
		21: "k_ESOMsg_Create",
		22: "k_ESOMsg_Update",
		23: "k_ESOMsg_Destroy",
		24: "k_ESOMsg_CacheSubscribed",
		25: "k_ESOMsg_CacheUnsubscribed",
		26: "k_ESOMsg_UpdateMultiple",
		27: "k_ESOMsg_CacheSubscriptionCheck",
		28: "k_ESOMsg_CacheSubscriptionRefresh",
	}
	ESOMsg_value = map[string]int32{
		"k_ESOMsg_Create":                   21,
		"k_ESOMsg_Update":                   22,
		"k_ESOMsg_Destroy":                  23,
		"k_ESOMsg_CacheSubscribed":          24,
		"k_ESOMsg_CacheUnsubscribed":        25,
		"k_ESOMsg_UpdateMultiple":           26,
		"k_ESOMsg_CacheSubscriptionCheck":   27,
		"k_ESOMsg_CacheSubscriptionRefresh": 28,
	}
)

func (x ESOMsg) Enum() *ESOMsg {
	p := new(ESOMsg)
	*p = x
	return p
}

func (x ESOMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESOMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[1].Descriptor()
}

func (ESOMsg) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[1]
}

func (x ESOMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ESOMsg) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ESOMsg(num)
	return nil
}

// Deprecated: Use ESOMsg.Descriptor instead.
func (ESOMsg) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{1}
}

type EGCBaseClientMsg int32

const (
	EGCBaseClientMsg_k_EMsgGCClientWelcome          EGCBaseClientMsg = 4004
	EGCBaseClientMsg_k_EMsgGCServerWelcome          EGCBaseClientMsg = 4005
	EGCBaseClientMsg_k_EMsgGCClientHello            EGCBaseClientMsg = 4006
	EGCBaseClientMsg_k_EMsgGCServerHello            EGCBaseClientMsg = 4007
	EGCBaseClientMsg_k_EMsgGCClientConnectionStatus EGCBaseClientMsg = 4009
	EGCBaseClientMsg_k_EMsgGCServerConnectionStatus EGCBaseClientMsg = 4010
	EGCBaseClientMsg_k_EMsgGCClientHelloPartner     EGCBaseClientMsg = 4011
	EGCBaseClientMsg_k_EMsgGCClientHelloPW          EGCBaseClientMsg = 4012
	EGCBaseClientMsg_k_EMsgGCClientHelloR2          EGCBaseClientMsg = 4013
	EGCBaseClientMsg_k_EMsgGCClientHelloR3          EGCBaseClientMsg = 4014
	EGCBaseClientMsg_k_EMsgGCClientHelloR4          EGCBaseClientMsg = 4015
)

// Enum value maps for EGCBaseClientMsg.
var (
	EGCBaseClientMsg_name = map[int32]string{
		4004: "k_EMsgGCClientWelcome",
		4005: "k_EMsgGCServerWelcome",
		4006: "k_EMsgGCClientHello",
		4007: "k_EMsgGCServerHello",
		4009: "k_EMsgGCClientConnectionStatus",
		4010: "k_EMsgGCServerConnectionStatus",
		4011: "k_EMsgGCClientHelloPartner",
		4012: "k_EMsgGCClientHelloPW",
		4013: "k_EMsgGCClientHelloR2",
		4014: "k_EMsgGCClientHelloR3",
		4015: "k_EMsgGCClientHelloR4",
	}
	EGCBaseClientMsg_value = map[string]int32{
		"k_EMsgGCClientWelcome":          4004,
		"k_EMsgGCServerWelcome":          4005,
		"k_EMsgGCClientHello":            4006,
		"k_EMsgGCServerHello":            4007,
		"k_EMsgGCClientConnectionStatus": 4009,
		"k_EMsgGCServerConnectionStatus": 4010,
		"k_EMsgGCClientHelloPartner":     4011,
		"k_EMsgGCClientHelloPW":          4012,
		"k_EMsgGCClientHelloR2":          4013,
		"k_EMsgGCClientHelloR3":          4014,
		"k_EMsgGCClientHelloR4":          4015,
	}
)

func (x EGCBaseClientMsg) Enum() *EGCBaseClientMsg {
	p := new(EGCBaseClientMsg)
	*p = x
	return p
}

func (x EGCBaseClientMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGCBaseClientMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[2].Descriptor()
}

func (EGCBaseClientMsg) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[2]
}

func (x EGCBaseClientMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EGCBaseClientMsg) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EGCBaseClientMsg(num)
	return nil
}

// Deprecated: Use EGCBaseClientMsg.Descriptor instead.
func (EGCBaseClientMsg) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{2}
}

type EGCToGCMsg int32

const (
	EGCToGCMsg_k_EGCToGCMsgMasterAck             EGCToGCMsg = 150
	EGCToGCMsg_k_EGCToGCMsgMasterAckResponse     EGCToGCMsg = 151
	EGCToGCMsg_k_EGCToGCMsgRouted                EGCToGCMsg = 152
	EGCToGCMsg_k_EGCToGCMsgRoutedReply           EGCToGCMsg = 153
	EGCToGCMsg_k_EMsgUpdateSessionIP             EGCToGCMsg = 154
	EGCToGCMsg_k_EMsgRequestSessionIP            EGCToGCMsg = 155
	EGCToGCMsg_k_EMsgRequestSessionIPResponse    EGCToGCMsg = 156
	EGCToGCMsg_k_EGCToGCMsgMasterStartupComplete EGCToGCMsg = 157
)

// Enum value maps for EGCToGCMsg.
var (
	EGCToGCMsg_name = map[int32]string{
		150: "k_EGCToGCMsgMasterAck",
		151: "k_EGCToGCMsgMasterAckResponse",
		152: "k_EGCToGCMsgRouted",
		153: "k_EGCToGCMsgRoutedReply",
		154: "k_EMsgUpdateSessionIP",
		155: "k_EMsgRequestSessionIP",
		156: "k_EMsgRequestSessionIPResponse",
		157: "k_EGCToGCMsgMasterStartupComplete",
	}
	EGCToGCMsg_value = map[string]int32{
		"k_EGCToGCMsgMasterAck":             150,
		"k_EGCToGCMsgMasterAckResponse":     151,
		"k_EGCToGCMsgRouted":                152,
		"k_EGCToGCMsgRoutedReply":           153,
		"k_EMsgUpdateSessionIP":             154,
		"k_EMsgRequestSessionIP":            155,
		"k_EMsgRequestSessionIPResponse":    156,
		"k_EGCToGCMsgMasterStartupComplete": 157,
	}
)

func (x EGCToGCMsg) Enum() *EGCToGCMsg {
	p := new(EGCToGCMsg)
	*p = x
	return p
}

func (x EGCToGCMsg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGCToGCMsg) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[3].Descriptor()
}

func (EGCToGCMsg) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[3]
}

func (x EGCToGCMsg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EGCToGCMsg) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EGCToGCMsg(num)
	return nil
}

// Deprecated: Use EGCToGCMsg.Descriptor instead.
func (EGCToGCMsg) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{3}
}

type ECommunityItemClass int32

const (
	ECommunityItemClass_k_ECommunityItemClass_Invalid           ECommunityItemClass = 0
	ECommunityItemClass_k_ECommunityItemClass_Badge             ECommunityItemClass = 1
	ECommunityItemClass_k_ECommunityItemClass_GameCard          ECommunityItemClass = 2
	ECommunityItemClass_k_ECommunityItemClass_ProfileBackground ECommunityItemClass = 3
	ECommunityItemClass_k_ECommunityItemClass_Emoticon          ECommunityItemClass = 4
	ECommunityItemClass_k_ECommunityItemClass_BoosterPack       ECommunityItemClass = 5
	ECommunityItemClass_k_ECommunityItemClass_Consumable        ECommunityItemClass = 6
	ECommunityItemClass_k_ECommunityItemClass_GameGoo           ECommunityItemClass = 7
	ECommunityItemClass_k_ECommunityItemClass_ProfileModifier   ECommunityItemClass = 8
	ECommunityItemClass_k_ECommunityItemClass_Scene             ECommunityItemClass = 9
	ECommunityItemClass_k_ECommunityItemClass_SalienItem        ECommunityItemClass = 10
)

// Enum value maps for ECommunityItemClass.
var (
	ECommunityItemClass_name = map[int32]string{
		0:  "k_ECommunityItemClass_Invalid",
		1:  "k_ECommunityItemClass_Badge",
		2:  "k_ECommunityItemClass_GameCard",
		3:  "k_ECommunityItemClass_ProfileBackground",
		4:  "k_ECommunityItemClass_Emoticon",
		5:  "k_ECommunityItemClass_BoosterPack",
		6:  "k_ECommunityItemClass_Consumable",
		7:  "k_ECommunityItemClass_GameGoo",
		8:  "k_ECommunityItemClass_ProfileModifier",
		9:  "k_ECommunityItemClass_Scene",
		10: "k_ECommunityItemClass_SalienItem",
	}
	ECommunityItemClass_value = map[string]int32{
		"k_ECommunityItemClass_Invalid":           0,
		"k_ECommunityItemClass_Badge":             1,
		"k_ECommunityItemClass_GameCard":          2,
		"k_ECommunityItemClass_ProfileBackground": 3,
		"k_ECommunityItemClass_Emoticon":          4,
		"k_ECommunityItemClass_BoosterPack":       5,
		"k_ECommunityItemClass_Consumable":        6,
		"k_ECommunityItemClass_GameGoo":           7,
		"k_ECommunityItemClass_ProfileModifier":   8,
		"k_ECommunityItemClass_Scene":             9,
		"k_ECommunityItemClass_SalienItem":        10,
	}
)

func (x ECommunityItemClass) Enum() *ECommunityItemClass {
	p := new(ECommunityItemClass)
	*p = x
	return p
}

func (x ECommunityItemClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECommunityItemClass) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[4].Descriptor()
}

func (ECommunityItemClass) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[4]
}

func (x ECommunityItemClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECommunityItemClass) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECommunityItemClass(num)
	return nil
}

// Deprecated: Use ECommunityItemClass.Descriptor instead.
func (ECommunityItemClass) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{4}
}

type ECommunityItemAttribute int32

const (
	ECommunityItemAttribute_k_ECommunityItemAttribute_Invalid               ECommunityItemAttribute = 0
	ECommunityItemAttribute_k_ECommunityItemAttribute_CardBorder            ECommunityItemAttribute = 1
	ECommunityItemAttribute_k_ECommunityItemAttribute_Level                 ECommunityItemAttribute = 2
	ECommunityItemAttribute_k_ECommunityItemAttribute_IssueNumber           ECommunityItemAttribute = 3
	ECommunityItemAttribute_k_ECommunityItemAttribute_TradableTime          ECommunityItemAttribute = 4
	ECommunityItemAttribute_k_ECommunityItemAttribute_StorePackageID        ECommunityItemAttribute = 5
	ECommunityItemAttribute_k_ECommunityItemAttribute_CommunityItemAppID    ECommunityItemAttribute = 6
	ECommunityItemAttribute_k_ECommunityItemAttribute_CommunityItemType     ECommunityItemAttribute = 7
	ECommunityItemAttribute_k_ECommunityItemAttribute_ProfileModiferEnabled ECommunityItemAttribute = 8
	ECommunityItemAttribute_k_ECommunityItemAttribute_ExpiryTime            ECommunityItemAttribute = 9
)

// Enum value maps for ECommunityItemAttribute.
var (
	ECommunityItemAttribute_name = map[int32]string{
		0: "k_ECommunityItemAttribute_Invalid",
		1: "k_ECommunityItemAttribute_CardBorder",
		2: "k_ECommunityItemAttribute_Level",
		3: "k_ECommunityItemAttribute_IssueNumber",
		4: "k_ECommunityItemAttribute_TradableTime",
		5: "k_ECommunityItemAttribute_StorePackageID",
		6: "k_ECommunityItemAttribute_CommunityItemAppID",
		7: "k_ECommunityItemAttribute_CommunityItemType",
		8: "k_ECommunityItemAttribute_ProfileModiferEnabled",
		9: "k_ECommunityItemAttribute_ExpiryTime",
	}
	ECommunityItemAttribute_value = map[string]int32{
		"k_ECommunityItemAttribute_Invalid":               0,
		"k_ECommunityItemAttribute_CardBorder":            1,
		"k_ECommunityItemAttribute_Level":                 2,
		"k_ECommunityItemAttribute_IssueNumber":           3,
		"k_ECommunityItemAttribute_TradableTime":          4,
		"k_ECommunityItemAttribute_StorePackageID":        5,
		"k_ECommunityItemAttribute_CommunityItemAppID":    6,
		"k_ECommunityItemAttribute_CommunityItemType":     7,
		"k_ECommunityItemAttribute_ProfileModiferEnabled": 8,
		"k_ECommunityItemAttribute_ExpiryTime":            9,
	}
)

func (x ECommunityItemAttribute) Enum() *ECommunityItemAttribute {
	p := new(ECommunityItemAttribute)
	*p = x
	return p
}

func (x ECommunityItemAttribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECommunityItemAttribute) Descriptor() protoreflect.EnumDescriptor {
	return file_gcsystemmsgs_proto_enumTypes[5].Descriptor()
}

func (ECommunityItemAttribute) Type() protoreflect.EnumType {
	return &file_gcsystemmsgs_proto_enumTypes[5]
}

func (x ECommunityItemAttribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECommunityItemAttribute) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECommunityItemAttribute(num)
	return nil
}

// Deprecated: Use ECommunityItemAttribute.Descriptor instead.
func (ECommunityItemAttribute) EnumDescriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{5}
}

type CMsgGCHVacVerificationChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steamid       *uint64                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid         *uint32                `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,3,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGCHVacVerificationChange) Reset() {
	*x = CMsgGCHVacVerificationChange{}
	mi := &file_gcsystemmsgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCHVacVerificationChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCHVacVerificationChange) ProtoMessage() {}

func (x *CMsgGCHVacVerificationChange) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCHVacVerificationChange.ProtoReflect.Descriptor instead.
func (*CMsgGCHVacVerificationChange) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgGCHVacVerificationChange) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CMsgGCHVacVerificationChange) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgGCHVacVerificationChange) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

type CMsgGCHAccountPhoneNumberChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steamid       *uint64                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid         *uint32                `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	PhoneId       *uint64                `protobuf:"varint,3,opt,name=phone_id,json=phoneId" json:"phone_id,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,4,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	IsIdentifying *bool                  `protobuf:"varint,5,opt,name=is_identifying,json=isIdentifying" json:"is_identifying,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGCHAccountPhoneNumberChange) Reset() {
	*x = CMsgGCHAccountPhoneNumberChange{}
	mi := &file_gcsystemmsgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCHAccountPhoneNumberChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCHAccountPhoneNumberChange) ProtoMessage() {}

func (x *CMsgGCHAccountPhoneNumberChange) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCHAccountPhoneNumberChange.ProtoReflect.Descriptor instead.
func (*CMsgGCHAccountPhoneNumberChange) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgGCHAccountPhoneNumberChange) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CMsgGCHAccountPhoneNumberChange) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgGCHAccountPhoneNumberChange) GetPhoneId() uint64 {
	if x != nil && x.PhoneId != nil {
		return *x.PhoneId
	}
	return 0
}

func (x *CMsgGCHAccountPhoneNumberChange) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

func (x *CMsgGCHAccountPhoneNumberChange) GetIsIdentifying() bool {
	if x != nil && x.IsIdentifying != nil {
		return *x.IsIdentifying
	}
	return false
}

type CMsgGCHInviteUserToLobby struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Steamid        *uint64                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid          *uint32                `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	SteamidInvited *uint64                `protobuf:"fixed64,3,opt,name=steamid_invited,json=steamidInvited" json:"steamid_invited,omitempty"`
	SteamidLobby   *uint64                `protobuf:"fixed64,4,opt,name=steamid_lobby,json=steamidLobby" json:"steamid_lobby,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CMsgGCHInviteUserToLobby) Reset() {
	*x = CMsgGCHInviteUserToLobby{}
	mi := &file_gcsystemmsgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCHInviteUserToLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCHInviteUserToLobby) ProtoMessage() {}

func (x *CMsgGCHInviteUserToLobby) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCHInviteUserToLobby.ProtoReflect.Descriptor instead.
func (*CMsgGCHInviteUserToLobby) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgGCHInviteUserToLobby) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CMsgGCHInviteUserToLobby) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgGCHInviteUserToLobby) GetSteamidInvited() uint64 {
	if x != nil && x.SteamidInvited != nil {
		return *x.SteamidInvited
	}
	return 0
}

func (x *CMsgGCHInviteUserToLobby) GetSteamidLobby() uint64 {
	if x != nil && x.SteamidLobby != nil {
		return *x.SteamidLobby
	}
	return 0
}

type CMsgGCHRecurringSubscriptionStatusChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steamid       *uint64                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid         *uint32                `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Agreementid   *uint64                `protobuf:"fixed64,3,opt,name=agreementid" json:"agreementid,omitempty"`
	Active        *bool                  `protobuf:"varint,4,opt,name=active" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) Reset() {
	*x = CMsgGCHRecurringSubscriptionStatusChange{}
	mi := &file_gcsystemmsgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCHRecurringSubscriptionStatusChange) ProtoMessage() {}

func (x *CMsgGCHRecurringSubscriptionStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCHRecurringSubscriptionStatusChange.ProtoReflect.Descriptor instead.
func (*CMsgGCHRecurringSubscriptionStatusChange) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) GetAgreementid() uint64 {
	if x != nil && x.Agreementid != nil {
		return *x.Agreementid
	}
	return 0
}

func (x *CMsgGCHRecurringSubscriptionStatusChange) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type CQuest_PublisherAddCommunityItemsToPlayer_Request struct {
	state          protoimpl.MessageState                                         `protogen:"open.v1"`
	Steamid        *uint64                                                        `protobuf:"varint,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid          *uint32                                                        `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	MatchItemType  *uint32                                                        `protobuf:"varint,3,opt,name=match_item_type,json=matchItemType" json:"match_item_type,omitempty"`
	MatchItemClass *uint32                                                        `protobuf:"varint,4,opt,name=match_item_class,json=matchItemClass" json:"match_item_class,omitempty"`
	PrefixItemName *string                                                        `protobuf:"bytes,5,opt,name=prefix_item_name,json=prefixItemName" json:"prefix_item_name,omitempty"`
	Attributes     []*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute `protobuf:"bytes,6,rep,name=attributes" json:"attributes,omitempty"`
	Note           *string                                                        `protobuf:"bytes,7,opt,name=note" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) Reset() {
	*x = CQuest_PublisherAddCommunityItemsToPlayer_Request{}
	mi := &file_gcsystemmsgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CQuest_PublisherAddCommunityItemsToPlayer_Request) ProtoMessage() {}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CQuest_PublisherAddCommunityItemsToPlayer_Request.ProtoReflect.Descriptor instead.
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{4}
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetMatchItemType() uint32 {
	if x != nil && x.MatchItemType != nil {
		return *x.MatchItemType
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetMatchItemClass() uint32 {
	if x != nil && x.MatchItemClass != nil {
		return *x.MatchItemClass
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetPrefixItemName() string {
	if x != nil && x.PrefixItemName != nil {
		return *x.PrefixItemName
	}
	return ""
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetAttributes() []*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type CQuest_PublisherAddCommunityItemsToPlayer_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsMatched  *uint32                `protobuf:"varint,1,opt,name=items_matched,json=itemsMatched" json:"items_matched,omitempty"`
	ItemsGranted  *uint32                `protobuf:"varint,2,opt,name=items_granted,json=itemsGranted" json:"items_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Response) Reset() {
	*x = CQuest_PublisherAddCommunityItemsToPlayer_Response{}
	mi := &file_gcsystemmsgs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CQuest_PublisherAddCommunityItemsToPlayer_Response) ProtoMessage() {}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CQuest_PublisherAddCommunityItemsToPlayer_Response.ProtoReflect.Descriptor instead.
func (*CQuest_PublisherAddCommunityItemsToPlayer_Response) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{5}
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Response) GetItemsMatched() uint32 {
	if x != nil && x.ItemsMatched != nil {
		return *x.ItemsMatched
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Response) GetItemsGranted() uint32 {
	if x != nil && x.ItemsGranted != nil {
		return *x.ItemsGranted
	}
	return 0
}

type CCommunity_GamePersonalDataCategoryInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              *string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	LocalizationToken *string                `protobuf:"bytes,2,opt,name=localization_token,json=localizationToken" json:"localization_token,omitempty"`
	TemplateFile      *string                `protobuf:"bytes,3,opt,name=template_file,json=templateFile" json:"template_file,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CCommunity_GamePersonalDataCategoryInfo) Reset() {
	*x = CCommunity_GamePersonalDataCategoryInfo{}
	mi := &file_gcsystemmsgs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_GamePersonalDataCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_GamePersonalDataCategoryInfo) ProtoMessage() {}

func (x *CCommunity_GamePersonalDataCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_GamePersonalDataCategoryInfo.ProtoReflect.Descriptor instead.
func (*CCommunity_GamePersonalDataCategoryInfo) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{6}
}

func (x *CCommunity_GamePersonalDataCategoryInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CCommunity_GamePersonalDataCategoryInfo) GetLocalizationToken() string {
	if x != nil && x.LocalizationToken != nil {
		return *x.LocalizationToken
	}
	return ""
}

func (x *CCommunity_GamePersonalDataCategoryInfo) GetTemplateFile() string {
	if x != nil && x.TemplateFile != nil {
		return *x.TemplateFile
	}
	return ""
}

type CCommunity_GetGamePersonalDataCategories_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCommunity_GetGamePersonalDataCategories_Request) Reset() {
	*x = CCommunity_GetGamePersonalDataCategories_Request{}
	mi := &file_gcsystemmsgs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_GetGamePersonalDataCategories_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_GetGamePersonalDataCategories_Request) ProtoMessage() {}

func (x *CCommunity_GetGamePersonalDataCategories_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_GetGamePersonalDataCategories_Request.ProtoReflect.Descriptor instead.
func (*CCommunity_GetGamePersonalDataCategories_Request) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{7}
}

func (x *CCommunity_GetGamePersonalDataCategories_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

type CCommunity_GetGamePersonalDataCategories_Response struct {
	state             protoimpl.MessageState                     `protogen:"open.v1"`
	Categories        []*CCommunity_GamePersonalDataCategoryInfo `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
	AppAssetsBasename *string                                    `protobuf:"bytes,2,opt,name=app_assets_basename,json=appAssetsBasename" json:"app_assets_basename,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CCommunity_GetGamePersonalDataCategories_Response) Reset() {
	*x = CCommunity_GetGamePersonalDataCategories_Response{}
	mi := &file_gcsystemmsgs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_GetGamePersonalDataCategories_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_GetGamePersonalDataCategories_Response) ProtoMessage() {}

func (x *CCommunity_GetGamePersonalDataCategories_Response) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_GetGamePersonalDataCategories_Response.ProtoReflect.Descriptor instead.
func (*CCommunity_GetGamePersonalDataCategories_Response) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{8}
}

func (x *CCommunity_GetGamePersonalDataCategories_Response) GetCategories() []*CCommunity_GamePersonalDataCategoryInfo {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CCommunity_GetGamePersonalDataCategories_Response) GetAppAssetsBasename() string {
	if x != nil && x.AppAssetsBasename != nil {
		return *x.AppAssetsBasename
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid       *uint64                `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ContinueToken *string                `protobuf:"bytes,4,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) Reset() {
	*x = CCommunity_GetGamePersonalDataEntries_Request{}
	mi := &file_gcsystemmsgs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_GetGamePersonalDataEntries_Request) ProtoMessage() {}

func (x *CCommunity_GetGamePersonalDataEntries_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_GetGamePersonalDataEntries_Request.ProtoReflect.Descriptor instead.
func (*CCommunity_GetGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{9}
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CCommunity_GetGamePersonalDataEntries_Request) GetContinueToken() string {
	if x != nil && x.ContinueToken != nil {
		return *x.ContinueToken
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gceresult     *uint32                `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	Entries       []string               `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	ContinueToken *string                `protobuf:"bytes,3,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	ContinueText  *string                `protobuf:"bytes,4,opt,name=continue_text,json=continueText" json:"continue_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) Reset() {
	*x = CCommunity_GetGamePersonalDataEntries_Response{}
	mi := &file_gcsystemmsgs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_GetGamePersonalDataEntries_Response) ProtoMessage() {}

func (x *CCommunity_GetGamePersonalDataEntries_Response) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_GetGamePersonalDataEntries_Response.ProtoReflect.Descriptor instead.
func (*CCommunity_GetGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{10}
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if x != nil && x.Gceresult != nil {
		return *x.Gceresult
	}
	return 0
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) GetContinueToken() string {
	if x != nil && x.ContinueToken != nil {
		return *x.ContinueToken
	}
	return ""
}

func (x *CCommunity_GetGamePersonalDataEntries_Response) GetContinueText() string {
	if x != nil && x.ContinueText != nil {
		return *x.ContinueText
	}
	return ""
}

type CCommunity_TerminateGamePersonalDataEntries_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid       *uint64                `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Request) Reset() {
	*x = CCommunity_TerminateGamePersonalDataEntries_Request{}
	mi := &file_gcsystemmsgs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_TerminateGamePersonalDataEntries_Request) ProtoMessage() {}

func (x *CCommunity_TerminateGamePersonalDataEntries_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_TerminateGamePersonalDataEntries_Request.ProtoReflect.Descriptor instead.
func (*CCommunity_TerminateGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{11}
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CCommunity_TerminateGamePersonalDataEntries_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gceresult     *uint32                `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Response) Reset() {
	*x = CCommunity_TerminateGamePersonalDataEntries_Response{}
	mi := &file_gcsystemmsgs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCommunity_TerminateGamePersonalDataEntries_Response) ProtoMessage() {}

func (x *CCommunity_TerminateGamePersonalDataEntries_Response) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCommunity_TerminateGamePersonalDataEntries_Response.ProtoReflect.Descriptor instead.
func (*CCommunity_TerminateGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{12}
}

func (x *CCommunity_TerminateGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if x != nil && x.Gceresult != nil {
		return *x.Gceresult
	}
	return 0
}

type CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *uint32                `protobuf:"varint,1,opt,name=attribute" json:"attribute,omitempty"`
	Value         *uint64                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) Reset() {
	*x = CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute{}
	mi := &file_gcsystemmsgs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) ProtoMessage() {}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_gcsystemmsgs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.ProtoReflect.Descriptor instead.
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) Descriptor() ([]byte, []int) {
	return file_gcsystemmsgs_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) GetAttribute() uint32 {
	if x != nil && x.Attribute != nil {
		return *x.Attribute
	}
	return 0
}

func (x *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_gcsystemmsgs_proto protoreflect.FileDescriptor

const file_gcsystemmsgs_proto_rawDesc = "" +
	"\n" +
	"\x12gcsystemmsgs.proto\"o\n" +
	"\x1cCMsgGCHVacVerificationChange\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12\x1f\n" +
	"\vis_verified\x18\x03 \x01(\bR\n" +
	"isVerified\"\xb4\x01\n" +
	"\x1fCMsgGCHAccountPhoneNumberChange\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12\x19\n" +
	"\bphone_id\x18\x03 \x01(\x04R\aphoneId\x12\x1f\n" +
	"\vis_verified\x18\x04 \x01(\bR\n" +
	"isVerified\x12%\n" +
	"\x0eis_identifying\x18\x05 \x01(\bR\risIdentifying\"\x98\x01\n" +
	"\x18CMsgGCHInviteUserToLobby\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12'\n" +
	"\x0fsteamid_invited\x18\x03 \x01(\x06R\x0esteamidInvited\x12#\n" +
	"\rsteamid_lobby\x18\x04 \x01(\x06R\fsteamidLobby\"\x94\x01\n" +
	"(CMsgGCHRecurringSubscriptionStatusChange\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12 \n" +
	"\vagreementid\x18\x03 \x01(\x06R\vagreementid\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"\x92\x03\n" +
	"1CQuest_PublisherAddCommunityItemsToPlayer_Request\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x04R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12&\n" +
	"\x0fmatch_item_type\x18\x03 \x01(\rR\rmatchItemType\x12(\n" +
	"\x10match_item_class\x18\x04 \x01(\rR\x0ematchItemClass\x12(\n" +
	"\x10prefix_item_name\x18\x05 \x01(\tR\x0eprefixItemName\x12\\\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2<.CQuest_PublisherAddCommunityItemsToPlayer_Request.AttributeR\n" +
	"attributes\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x1a?\n" +
	"\tAttribute\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\rR\tattribute\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"~\n" +
	"2CQuest_PublisherAddCommunityItemsToPlayer_Response\x12#\n" +
	"\ritems_matched\x18\x01 \x01(\rR\fitemsMatched\x12#\n" +
	"\ritems_granted\x18\x02 \x01(\rR\fitemsGranted\"\x91\x01\n" +
	"'CCommunity_GamePersonalDataCategoryInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x12localization_token\x18\x02 \x01(\tR\x11localizationToken\x12#\n" +
	"\rtemplate_file\x18\x03 \x01(\tR\ftemplateFile\"H\n" +
	"0CCommunity_GetGamePersonalDataCategories_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\"\xad\x01\n" +
	"1CCommunity_GetGamePersonalDataCategories_Response\x12H\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2(.CCommunity_GamePersonalDataCategoryInfoR\n" +
	"categories\x12.\n" +
	"\x13app_assets_basename\x18\x02 \x01(\tR\x11appAssetsBasename\"\x9a\x01\n" +
	"-CCommunity_GetGamePersonalDataEntries_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x18\n" +
	"\asteamid\x18\x02 \x01(\x04R\asteamid\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12%\n" +
	"\x0econtinue_token\x18\x04 \x01(\tR\rcontinueToken\"\xb4\x01\n" +
	".CCommunity_GetGamePersonalDataEntries_Response\x12\x1c\n" +
	"\tgceresult\x18\x01 \x01(\rR\tgceresult\x12\x18\n" +
	"\aentries\x18\x02 \x03(\tR\aentries\x12%\n" +
	"\x0econtinue_token\x18\x03 \x01(\tR\rcontinueToken\x12#\n" +
	"\rcontinue_text\x18\x04 \x01(\tR\fcontinueText\"e\n" +
	"3CCommunity_TerminateGamePersonalDataEntries_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x18\n" +
	"\asteamid\x18\x02 \x01(\x04R\asteamid\"T\n" +
	"4CCommunity_TerminateGamePersonalDataEntries_Response\x12\x1c\n" +
	"\tgceresult\x18\x01 \x01(\rR\tgceresult*\xc2\x18\n" +
	"\fEGCSystemMsg\x12\x13\n" +
	"\x0fk_EGCMsgInvalid\x10\x00\x12\x11\n" +
	"\rk_EGCMsgMulti\x10\x01\x12\x18\n" +
	"\x14k_EGCMsgGenericReply\x10\n" +
	"\x12\x16\n" +
	"\x12k_EGCMsgSystemBase\x102\x12\x1e\n" +
	"\x1ak_EGCMsgAchievementAwarded\x103\x12\x16\n" +
	"\x12k_EGCMsgConCommand\x104\x12\x18\n" +
	"\x14k_EGCMsgStartPlaying\x105\x12\x17\n" +
	"\x13k_EGCMsgStopPlaying\x106\x12\x1b\n" +
	"\x17k_EGCMsgStartGameserver\x107\x12\x1a\n" +
	"\x16k_EGCMsgStopGameserver\x108\x12\x15\n" +
	"\x11k_EGCMsgWGRequest\x109\x12\x16\n" +
	"\x12k_EGCMsgWGResponse\x10:\x12\"\n" +
	"\x1ek_EGCMsgGetUserGameStatsSchema\x10;\x12*\n" +
	"&k_EGCMsgGetUserGameStatsSchemaResponse\x10<\x12\"\n" +
	"\x1ek_EGCMsgGetUserStatsDEPRECATED\x10=\x12 \n" +
	"\x1ck_EGCMsgGetUserStatsResponse\x10>\x12\x1a\n" +
	"\x16k_EGCMsgAppInfoUpdated\x10?\x12\x1b\n" +
	"\x17k_EGCMsgValidateSession\x10@\x12#\n" +
	"\x1fk_EGCMsgValidateSessionResponse\x10A\x12\"\n" +
	"\x1ek_EGCMsgLookupAccountFromInput\x10B\x12\x1b\n" +
	"\x17k_EGCMsgSendHTTPRequest\x10C\x12#\n" +
	"\x1fk_EGCMsgSendHTTPRequestResponse\x10D\x12\x18\n" +
	"\x14k_EGCMsgPreTestSetup\x10E\x12\x1f\n" +
	"\x1bk_EGCMsgRecordSupportAction\x10F\x12(\n" +
	"$k_EGCMsgGetAccountDetails_DEPRECATED\x10G\x12\"\n" +
	"\x1ek_EGCMsgReceiveInterAppMessage\x10I\x12\x18\n" +
	"\x14k_EGCMsgFindAccounts\x10J\x12\x15\n" +
	"\x11k_EGCMsgPostAlert\x10K\x12\x17\n" +
	"\x13k_EGCMsgGetLicenses\x10L\x12\x18\n" +
	"\x14k_EGCMsgGetUserStats\x10M\x12\x17\n" +
	"\x13k_EGCMsgGetCommands\x10N\x12\x1f\n" +
	"\x1bk_EGCMsgGetCommandsResponse\x10O\x12\x1a\n" +
	"\x16k_EGCMsgAddFreeLicense\x10P\x12\"\n" +
	"\x1ek_EGCMsgAddFreeLicenseResponse\x10Q\x12\x19\n" +
	"\x15k_EGCMsgGetIPLocation\x10R\x12!\n" +
	"\x1dk_EGCMsgGetIPLocationResponse\x10S\x12\x1d\n" +
	"\x19k_EGCMsgSystemStatsSchema\x10T\x12\x1a\n" +
	"\x16k_EGCMsgGetSystemStats\x10U\x12\"\n" +
	"\x1ek_EGCMsgGetSystemStatsResponse\x10V\x12\x15\n" +
	"\x11k_EGCMsgSendEmail\x10W\x12\x1d\n" +
	"\x19k_EGCMsgSendEmailResponse\x10X\x12\x1c\n" +
	"\x18k_EGCMsgGetEmailTemplate\x10Y\x12$\n" +
	" k_EGCMsgGetEmailTemplateResponse\x10Z\x12\x1a\n" +
	"\x16k_EGCMsgGrantGuestPass\x10[\x12\"\n" +
	"\x1ek_EGCMsgGrantGuestPassResponse\x10\\\x12\x1d\n" +
	"\x19k_EGCMsgGetAccountDetails\x10]\x12%\n" +
	"!k_EGCMsgGetAccountDetailsResponse\x10^\x12\x1b\n" +
	"\x17k_EGCMsgGetPersonaNames\x10_\x12#\n" +
	"\x1fk_EGCMsgGetPersonaNamesResponse\x10`\x12\x18\n" +
	"\x14k_EGCMsgMultiplexMsg\x10a\x12 \n" +
	"\x1ck_EGCMsgMultiplexMsgResponse\x10b\x12$\n" +
	" k_EGCMsgWebAPIRegisterInterfaces\x10e\x12\x1c\n" +
	"\x18k_EGCMsgWebAPIJobRequest\x10f\x12(\n" +
	"$k_EGCMsgWebAPIJobRequestHttpResponse\x10h\x12+\n" +
	"'k_EGCMsgWebAPIJobRequestForwardResponse\x10i\x12\x19\n" +
	"\x14k_EGCMsgMemCachedGet\x10\xc8\x01\x12!\n" +
	"\x1ck_EGCMsgMemCachedGetResponse\x10\xc9\x01\x12\x19\n" +
	"\x14k_EGCMsgMemCachedSet\x10\xca\x01\x12\x1c\n" +
	"\x17k_EGCMsgMemCachedDelete\x10\xcb\x01\x12\x1b\n" +
	"\x16k_EGCMsgMemCachedStats\x10\xcc\x01\x12#\n" +
	"\x1ek_EGCMsgMemCachedStatsResponse\x10\xcd\x01\x12\x1f\n" +
	"\x1ak_EGCMsgMasterSetDirectory\x10\xdc\x01\x12'\n" +
	"\"k_EGCMsgMasterSetDirectoryResponse\x10\xdd\x01\x12#\n" +
	"\x1ek_EGCMsgMasterSetWebAPIRouting\x10\xde\x01\x12+\n" +
	"&k_EGCMsgMasterSetWebAPIRoutingResponse\x10\xdf\x01\x12&\n" +
	"!k_EGCMsgMasterSetClientMsgRouting\x10\xe0\x01\x12.\n" +
	")k_EGCMsgMasterSetClientMsgRoutingResponse\x10\xe1\x01\x12\x17\n" +
	"\x12k_EGCMsgSetOptions\x10\xe2\x01\x12\x1f\n" +
	"\x1ak_EGCMsgSetOptionsResponse\x10\xe3\x01\x12\x18\n" +
	"\x13k_EGCMsgSystemBase2\x10\xf4\x03\x12#\n" +
	"\x1ek_EGCMsgGetPurchaseTrustStatus\x10\xf5\x03\x12+\n" +
	"&k_EGCMsgGetPurchaseTrustStatusResponse\x10\xf6\x03\x12\x1a\n" +
	"\x15k_EGCMsgUpdateSession\x10\xf7\x03\x12%\n" +
	" k_EGCMsgGCAccountVacStatusChange\x10\xf8\x03\x12\x1c\n" +
	"\x17k_EGCMsgCheckFriendship\x10\xf9\x03\x12$\n" +
	"\x1fk_EGCMsgCheckFriendshipResponse\x10\xfa\x03\x12\"\n" +
	"\x1dk_EGCMsgGetPartnerAccountLink\x10\xfb\x03\x12*\n" +
	"%k_EGCMsgGetPartnerAccountLinkResponse\x10\xfc\x03\x12\x1f\n" +
	"\x1ak_EGCMsgDPPartnerMicroTxns\x10\x80\x04\x12'\n" +
	"\"k_EGCMsgDPPartnerMicroTxnsResponse\x10\x81\x04\x12\"\n" +
	"\x1dk_EGCMsgVacVerificationChange\x10\x86\x04\x12%\n" +
	" k_EGCMsgAccountPhoneNumberChange\x10\x87\x04\x12\x1e\n" +
	"\x19k_EGCMsgInviteUserToLobby\x10\x8b\x04\x121\n" +
	",k_EGCMsgGetGamePersonalDataCategoriesRequest\x10\x8c\x04\x122\n" +
	"-k_EGCMsgGetGamePersonalDataCategoriesResponse\x10\x8d\x04\x12.\n" +
	")k_EGCMsgGetGamePersonalDataEntriesRequest\x10\x8e\x04\x12/\n" +
	"*k_EGCMsgGetGamePersonalDataEntriesResponse\x10\x8f\x04\x124\n" +
	"/k_EGCMsgTerminateGamePersonalDataEntriesRequest\x10\x90\x04\x125\n" +
	"0k_EGCMsgTerminateGamePersonalDataEntriesResponse\x10\x91\x04\x12.\n" +
	")k_EGCMsgRecurringSubscriptionStatusChange\x10\x92\x04\x12 \n" +
	"\x1bk_EGCMsgDirectServiceMethod\x10\x93\x04\x12(\n" +
	"#k_EGCMsgDirectServiceMethodResponse\x10\x94\x04*\xef\x01\n" +
	"\x06ESOMsg\x12\x13\n" +
	"\x0fk_ESOMsg_Create\x10\x15\x12\x13\n" +
	"\x0fk_ESOMsg_Update\x10\x16\x12\x14\n" +
	"\x10k_ESOMsg_Destroy\x10\x17\x12\x1c\n" +
	"\x18k_ESOMsg_CacheSubscribed\x10\x18\x12\x1e\n" +
	"\x1ak_ESOMsg_CacheUnsubscribed\x10\x19\x12\x1b\n" +
	"\x17k_ESOMsg_UpdateMultiple\x10\x1a\x12#\n" +
	"\x1fk_ESOMsg_CacheSubscriptionCheck\x10\x1b\x12%\n" +
	"!k_ESOMsg_CacheSubscriptionRefresh\x10\x1c*\xd9\x02\n" +
	"\x10EGCBaseClientMsg\x12\x1a\n" +
	"\x15k_EMsgGCClientWelcome\x10\xa4\x1f\x12\x1a\n" +
	"\x15k_EMsgGCServerWelcome\x10\xa5\x1f\x12\x18\n" +
	"\x13k_EMsgGCClientHello\x10\xa6\x1f\x12\x18\n" +
	"\x13k_EMsgGCServerHello\x10\xa7\x1f\x12#\n" +
	"\x1ek_EMsgGCClientConnectionStatus\x10\xa9\x1f\x12#\n" +
	"\x1ek_EMsgGCServerConnectionStatus\x10\xaa\x1f\x12\x1f\n" +
	"\x1ak_EMsgGCClientHelloPartner\x10\xab\x1f\x12\x1a\n" +
	"\x15k_EMsgGCClientHelloPW\x10\xac\x1f\x12\x1a\n" +
	"\x15k_EMsgGCClientHelloR2\x10\xad\x1f\x12\x1a\n" +
	"\x15k_EMsgGCClientHelloR3\x10\xae\x1f\x12\x1a\n" +
	"\x15k_EMsgGCClientHelloR4\x10\xaf\x1f*\x89\x02\n" +
	"\n" +
	"EGCToGCMsg\x12\x1a\n" +
	"\x15k_EGCToGCMsgMasterAck\x10\x96\x01\x12\"\n" +
	"\x1dk_EGCToGCMsgMasterAckResponse\x10\x97\x01\x12\x17\n" +
	"\x12k_EGCToGCMsgRouted\x10\x98\x01\x12\x1c\n" +
	"\x17k_EGCToGCMsgRoutedReply\x10\x99\x01\x12\x1a\n" +
	"\x15k_EMsgUpdateSessionIP\x10\x9a\x01\x12\x1b\n" +
	"\x16k_EMsgRequestSessionIP\x10\x9b\x01\x12#\n" +
	"\x1ek_EMsgRequestSessionIPResponse\x10\x9c\x01\x12&\n" +
	"!k_EGCToGCMsgMasterStartupComplete\x10\x9d\x01*\xb0\x03\n" +
	"\x13ECommunityItemClass\x12!\n" +
	"\x1dk_ECommunityItemClass_Invalid\x10\x00\x12\x1f\n" +
	"\x1bk_ECommunityItemClass_Badge\x10\x01\x12\"\n" +
	"\x1ek_ECommunityItemClass_GameCard\x10\x02\x12+\n" +
	"'k_ECommunityItemClass_ProfileBackground\x10\x03\x12\"\n" +
	"\x1ek_ECommunityItemClass_Emoticon\x10\x04\x12%\n" +
	"!k_ECommunityItemClass_BoosterPack\x10\x05\x12$\n" +
	" k_ECommunityItemClass_Consumable\x10\x06\x12!\n" +
	"\x1dk_ECommunityItemClass_GameGoo\x10\a\x12)\n" +
	"%k_ECommunityItemClass_ProfileModifier\x10\b\x12\x1f\n" +
	"\x1bk_ECommunityItemClass_Scene\x10\t\x12$\n" +
	" k_ECommunityItemClass_SalienItem\x10\n" +
	"*\xd6\x03\n" +
	"\x17ECommunityItemAttribute\x12%\n" +
	"!k_ECommunityItemAttribute_Invalid\x10\x00\x12(\n" +
	"$k_ECommunityItemAttribute_CardBorder\x10\x01\x12#\n" +
	"\x1fk_ECommunityItemAttribute_Level\x10\x02\x12)\n" +
	"%k_ECommunityItemAttribute_IssueNumber\x10\x03\x12*\n" +
	"&k_ECommunityItemAttribute_TradableTime\x10\x04\x12,\n" +
	"(k_ECommunityItemAttribute_StorePackageID\x10\x05\x120\n" +
	",k_ECommunityItemAttribute_CommunityItemAppID\x10\x06\x12/\n" +
	"+k_ECommunityItemAttribute_CommunityItemType\x10\a\x123\n" +
	"/k_ECommunityItemAttribute_ProfileModiferEnabled\x10\b\x12(\n" +
	"$k_ECommunityItemAttribute_ExpiryTime\x10\t"

var (
	file_gcsystemmsgs_proto_rawDescOnce sync.Once
	file_gcsystemmsgs_proto_rawDescData []byte
)

func file_gcsystemmsgs_proto_rawDescGZIP() []byte {
	file_gcsystemmsgs_proto_rawDescOnce.Do(func() {
		file_gcsystemmsgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gcsystemmsgs_proto_rawDesc), len(file_gcsystemmsgs_proto_rawDesc)))
	})
	return file_gcsystemmsgs_proto_rawDescData
}

var file_gcsystemmsgs_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_gcsystemmsgs_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gcsystemmsgs_proto_goTypes = []any{
	(EGCSystemMsg)(0),                                                   // 0: EGCSystemMsg
	(ESOMsg)(0),                                                         // 1: ESOMsg
	(EGCBaseClientMsg)(0),                                               // 2: EGCBaseClientMsg
	(EGCToGCMsg)(0),                                                     // 3: EGCToGCMsg
	(ECommunityItemClass)(0),                                            // 4: ECommunityItemClass
	(ECommunityItemAttribute)(0),                                        // 5: ECommunityItemAttribute
	(*CMsgGCHVacVerificationChange)(nil),                                // 6: CMsgGCHVacVerificationChange
	(*CMsgGCHAccountPhoneNumberChange)(nil),                             // 7: CMsgGCHAccountPhoneNumberChange
	(*CMsgGCHInviteUserToLobby)(nil),                                    // 8: CMsgGCHInviteUserToLobby
	(*CMsgGCHRecurringSubscriptionStatusChange)(nil),                    // 9: CMsgGCHRecurringSubscriptionStatusChange
	(*CQuest_PublisherAddCommunityItemsToPlayer_Request)(nil),           // 10: CQuest_PublisherAddCommunityItemsToPlayer_Request
	(*CQuest_PublisherAddCommunityItemsToPlayer_Response)(nil),          // 11: CQuest_PublisherAddCommunityItemsToPlayer_Response
	(*CCommunity_GamePersonalDataCategoryInfo)(nil),                     // 12: CCommunity_GamePersonalDataCategoryInfo
	(*CCommunity_GetGamePersonalDataCategories_Request)(nil),            // 13: CCommunity_GetGamePersonalDataCategories_Request
	(*CCommunity_GetGamePersonalDataCategories_Response)(nil),           // 14: CCommunity_GetGamePersonalDataCategories_Response
	(*CCommunity_GetGamePersonalDataEntries_Request)(nil),               // 15: CCommunity_GetGamePersonalDataEntries_Request
	(*CCommunity_GetGamePersonalDataEntries_Response)(nil),              // 16: CCommunity_GetGamePersonalDataEntries_Response
	(*CCommunity_TerminateGamePersonalDataEntries_Request)(nil),         // 17: CCommunity_TerminateGamePersonalDataEntries_Request
	(*CCommunity_TerminateGamePersonalDataEntries_Response)(nil),        // 18: CCommunity_TerminateGamePersonalDataEntries_Response
	(*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute)(nil), // 19: CQuest_PublisherAddCommunityItemsToPlayer_Request.Attribute
}
var file_gcsystemmsgs_proto_depIdxs = []int32{
	19, // 0: CQuest_PublisherAddCommunityItemsToPlayer_Request.attributes:type_name -> CQuest_PublisherAddCommunityItemsToPlayer_Request.Attribute
	12, // 1: CCommunity_GetGamePersonalDataCategories_Response.categories:type_name -> CCommunity_GamePersonalDataCategoryInfo
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_gcsystemmsgs_proto_init() }
func file_gcsystemmsgs_proto_init() {
	if File_gcsystemmsgs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcsystemmsgs_proto_rawDesc), len(file_gcsystemmsgs_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gcsystemmsgs_proto_goTypes,
		DependencyIndexes: file_gcsystemmsgs_proto_depIdxs,
		EnumInfos:         file_gcsystemmsgs_proto_enumTypes,
		MessageInfos:      file_gcsystemmsgs_proto_msgTypes,
	}.Build()
	File_gcsystemmsgs_proto = out.File
	file_gcsystemmsgs_proto_goTypes = nil
	file_gcsystemmsgs_proto_depIdxs = nil
}
