// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: steammessages_parental.steamclient.proto

package unified

import (
	
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParentalApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	IsAllowed     *bool                  `protobuf:"varint,2,opt,name=is_allowed,json=isAllowed" json:"is_allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentalApp) Reset() {
	*x = ParentalApp{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentalApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentalApp) ProtoMessage() {}

func (x *ParentalApp) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentalApp.ProtoReflect.Descriptor instead.
func (*ParentalApp) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{0}
}

func (x *ParentalApp) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *ParentalApp) GetIsAllowed() bool {
	if x != nil && x.IsAllowed != nil {
		return *x.IsAllowed
	}
	return false
}

type ParentalSettings struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Steamid                *uint64                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ApplistBaseId          *uint32                `protobuf:"varint,2,opt,name=applist_base_id,json=applistBaseId" json:"applist_base_id,omitempty"`
	ApplistBaseDescription *string                `protobuf:"bytes,3,opt,name=applist_base_description,json=applistBaseDescription" json:"applist_base_description,omitempty"`
	ApplistBase            []*ParentalApp         `protobuf:"bytes,4,rep,name=applist_base,json=applistBase" json:"applist_base,omitempty"`
	ApplistCustom          []*ParentalApp         `protobuf:"bytes,5,rep,name=applist_custom,json=applistCustom" json:"applist_custom,omitempty"`
	Passwordhashtype       *uint32                `protobuf:"varint,6,opt,name=passwordhashtype" json:"passwordhashtype,omitempty"`
	Salt                   []byte                 `protobuf:"bytes,7,opt,name=salt" json:"salt,omitempty"`
	Passwordhash           []byte                 `protobuf:"bytes,8,opt,name=passwordhash" json:"passwordhash,omitempty"`
	IsEnabled              *bool                  `protobuf:"varint,9,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	EnabledFeatures        *uint32                `protobuf:"varint,10,opt,name=enabled_features,json=enabledFeatures" json:"enabled_features,omitempty"`
	RecoveryEmail          *string                `protobuf:"bytes,11,opt,name=recovery_email,json=recoveryEmail" json:"recovery_email,omitempty"`
	IsSiteLicenseLock      *bool                  `protobuf:"varint,12,opt,name=is_site_license_lock,json=isSiteLicenseLock" json:"is_site_license_lock,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ParentalSettings) Reset() {
	*x = ParentalSettings{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentalSettings) ProtoMessage() {}

func (x *ParentalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentalSettings.ProtoReflect.Descriptor instead.
func (*ParentalSettings) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{1}
}

func (x *ParentalSettings) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *ParentalSettings) GetApplistBaseId() uint32 {
	if x != nil && x.ApplistBaseId != nil {
		return *x.ApplistBaseId
	}
	return 0
}

func (x *ParentalSettings) GetApplistBaseDescription() string {
	if x != nil && x.ApplistBaseDescription != nil {
		return *x.ApplistBaseDescription
	}
	return ""
}

func (x *ParentalSettings) GetApplistBase() []*ParentalApp {
	if x != nil {
		return x.ApplistBase
	}
	return nil
}

func (x *ParentalSettings) GetApplistCustom() []*ParentalApp {
	if x != nil {
		return x.ApplistCustom
	}
	return nil
}

func (x *ParentalSettings) GetPasswordhashtype() uint32 {
	if x != nil && x.Passwordhashtype != nil {
		return *x.Passwordhashtype
	}
	return 0
}

func (x *ParentalSettings) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *ParentalSettings) GetPasswordhash() []byte {
	if x != nil {
		return x.Passwordhash
	}
	return nil
}

func (x *ParentalSettings) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *ParentalSettings) GetEnabledFeatures() uint32 {
	if x != nil && x.EnabledFeatures != nil {
		return *x.EnabledFeatures
	}
	return 0
}

func (x *ParentalSettings) GetRecoveryEmail() string {
	if x != nil && x.RecoveryEmail != nil {
		return *x.RecoveryEmail
	}
	return ""
}

func (x *ParentalSettings) GetIsSiteLicenseLock() bool {
	if x != nil && x.IsSiteLicenseLock != nil {
		return *x.IsSiteLicenseLock
	}
	return false
}

type CParental_EnableParentalSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      *string                `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Settings      *ParentalSettings      `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	Sessionid     *string                `protobuf:"bytes,3,opt,name=sessionid" json:"sessionid,omitempty"`
	Enablecode    *uint32                `protobuf:"varint,4,opt,name=enablecode" json:"enablecode,omitempty"`
	Steamid       *uint64                `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_EnableParentalSettings_Request) Reset() {
	*x = CParental_EnableParentalSettings_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_EnableParentalSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_EnableParentalSettings_Request) ProtoMessage() {}

func (x *CParental_EnableParentalSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_EnableParentalSettings_Request.ProtoReflect.Descriptor instead.
func (*CParental_EnableParentalSettings_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{2}
}

func (x *CParental_EnableParentalSettings_Request) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_EnableParentalSettings_Request) GetSettings() *ParentalSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CParental_EnableParentalSettings_Request) GetSessionid() string {
	if x != nil && x.Sessionid != nil {
		return *x.Sessionid
	}
	return ""
}

func (x *CParental_EnableParentalSettings_Request) GetEnablecode() uint32 {
	if x != nil && x.Enablecode != nil {
		return *x.Enablecode
	}
	return 0
}

func (x *CParental_EnableParentalSettings_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CParental_EnableParentalSettings_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_EnableParentalSettings_Response) Reset() {
	*x = CParental_EnableParentalSettings_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_EnableParentalSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_EnableParentalSettings_Response) ProtoMessage() {}

func (x *CParental_EnableParentalSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_EnableParentalSettings_Response.ProtoReflect.Descriptor instead.
func (*CParental_EnableParentalSettings_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{3}
}

type CParental_DisableParentalSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      *string                `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Steamid       *uint64                `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_DisableParentalSettings_Request) Reset() {
	*x = CParental_DisableParentalSettings_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_DisableParentalSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_DisableParentalSettings_Request) ProtoMessage() {}

func (x *CParental_DisableParentalSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_DisableParentalSettings_Request.ProtoReflect.Descriptor instead.
func (*CParental_DisableParentalSettings_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{4}
}

func (x *CParental_DisableParentalSettings_Request) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_DisableParentalSettings_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CParental_DisableParentalSettings_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_DisableParentalSettings_Response) Reset() {
	*x = CParental_DisableParentalSettings_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_DisableParentalSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_DisableParentalSettings_Response) ProtoMessage() {}

func (x *CParental_DisableParentalSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_DisableParentalSettings_Response.ProtoReflect.Descriptor instead.
func (*CParental_DisableParentalSettings_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{5}
}

type CParental_GetParentalSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steamid       *uint64                `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_GetParentalSettings_Request) Reset() {
	*x = CParental_GetParentalSettings_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_GetParentalSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_GetParentalSettings_Request) ProtoMessage() {}

func (x *CParental_GetParentalSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_GetParentalSettings_Request.ProtoReflect.Descriptor instead.
func (*CParental_GetParentalSettings_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{6}
}

func (x *CParental_GetParentalSettings_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CParental_GetParentalSettings_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *ParentalSettings      `protobuf:"bytes,1,opt,name=settings" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_GetParentalSettings_Response) Reset() {
	*x = CParental_GetParentalSettings_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_GetParentalSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_GetParentalSettings_Response) ProtoMessage() {}

func (x *CParental_GetParentalSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_GetParentalSettings_Response.ProtoReflect.Descriptor instead.
func (*CParental_GetParentalSettings_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{7}
}

func (x *CParental_GetParentalSettings_Response) GetSettings() *ParentalSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CParental_GetSignedParentalSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      *uint32                `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_GetSignedParentalSettings_Request) Reset() {
	*x = CParental_GetSignedParentalSettings_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_GetSignedParentalSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_GetSignedParentalSettings_Request) ProtoMessage() {}

func (x *CParental_GetSignedParentalSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_GetSignedParentalSettings_Request.ProtoReflect.Descriptor instead.
func (*CParental_GetSignedParentalSettings_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{8}
}

func (x *CParental_GetSignedParentalSettings_Request) GetPriority() uint32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

type CParental_GetSignedParentalSettings_Response struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SerializedSettings []byte                 `protobuf:"bytes,1,opt,name=serialized_settings,json=serializedSettings" json:"serialized_settings,omitempty"`
	Signature          []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CParental_GetSignedParentalSettings_Response) Reset() {
	*x = CParental_GetSignedParentalSettings_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_GetSignedParentalSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_GetSignedParentalSettings_Response) ProtoMessage() {}

func (x *CParental_GetSignedParentalSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_GetSignedParentalSettings_Response.ProtoReflect.Descriptor instead.
func (*CParental_GetSignedParentalSettings_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{9}
}

func (x *CParental_GetSignedParentalSettings_Response) GetSerializedSettings() []byte {
	if x != nil {
		return x.SerializedSettings
	}
	return nil
}

func (x *CParental_GetSignedParentalSettings_Response) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CParental_SetParentalSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      *string                `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Settings      *ParentalSettings      `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	NewPassword   *string                `protobuf:"bytes,3,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
	Sessionid     *string                `protobuf:"bytes,4,opt,name=sessionid" json:"sessionid,omitempty"`
	Steamid       *uint64                `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_SetParentalSettings_Request) Reset() {
	*x = CParental_SetParentalSettings_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_SetParentalSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_SetParentalSettings_Request) ProtoMessage() {}

func (x *CParental_SetParentalSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_SetParentalSettings_Request.ProtoReflect.Descriptor instead.
func (*CParental_SetParentalSettings_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{10}
}

func (x *CParental_SetParentalSettings_Request) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_SetParentalSettings_Request) GetSettings() *ParentalSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CParental_SetParentalSettings_Request) GetNewPassword() string {
	if x != nil && x.NewPassword != nil {
		return *x.NewPassword
	}
	return ""
}

func (x *CParental_SetParentalSettings_Request) GetSessionid() string {
	if x != nil && x.Sessionid != nil {
		return *x.Sessionid
	}
	return ""
}

func (x *CParental_SetParentalSettings_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CParental_SetParentalSettings_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_SetParentalSettings_Response) Reset() {
	*x = CParental_SetParentalSettings_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_SetParentalSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_SetParentalSettings_Response) ProtoMessage() {}

func (x *CParental_SetParentalSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_SetParentalSettings_Response.ProtoReflect.Descriptor instead.
func (*CParental_SetParentalSettings_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{11}
}

type CParental_ValidateToken_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlockToken   *string                `protobuf:"bytes,1,opt,name=unlock_token,json=unlockToken" json:"unlock_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_ValidateToken_Request) Reset() {
	*x = CParental_ValidateToken_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ValidateToken_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ValidateToken_Request) ProtoMessage() {}

func (x *CParental_ValidateToken_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ValidateToken_Request.ProtoReflect.Descriptor instead.
func (*CParental_ValidateToken_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{12}
}

func (x *CParental_ValidateToken_Request) GetUnlockToken() string {
	if x != nil && x.UnlockToken != nil {
		return *x.UnlockToken
	}
	return ""
}

type CParental_ValidateToken_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_ValidateToken_Response) Reset() {
	*x = CParental_ValidateToken_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ValidateToken_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ValidateToken_Response) ProtoMessage() {}

func (x *CParental_ValidateToken_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ValidateToken_Response.ProtoReflect.Descriptor instead.
func (*CParental_ValidateToken_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{13}
}

type CParental_ValidatePassword_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Password            *string                `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Session             *string                `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
	SendUnlockOnSuccess *bool                  `protobuf:"varint,3,opt,name=send_unlock_on_success,json=sendUnlockOnSuccess" json:"send_unlock_on_success,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CParental_ValidatePassword_Request) Reset() {
	*x = CParental_ValidatePassword_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ValidatePassword_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ValidatePassword_Request) ProtoMessage() {}

func (x *CParental_ValidatePassword_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ValidatePassword_Request.ProtoReflect.Descriptor instead.
func (*CParental_ValidatePassword_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{14}
}

func (x *CParental_ValidatePassword_Request) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_ValidatePassword_Request) GetSession() string {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return ""
}

func (x *CParental_ValidatePassword_Request) GetSendUnlockOnSuccess() bool {
	if x != nil && x.SendUnlockOnSuccess != nil {
		return *x.SendUnlockOnSuccess
	}
	return false
}

type CParental_ValidatePassword_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_ValidatePassword_Response) Reset() {
	*x = CParental_ValidatePassword_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ValidatePassword_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ValidatePassword_Response) ProtoMessage() {}

func (x *CParental_ValidatePassword_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ValidatePassword_Response.ProtoReflect.Descriptor instead.
func (*CParental_ValidatePassword_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{15}
}

func (x *CParental_ValidatePassword_Response) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type CParental_LockClient_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *string                `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_LockClient_Request) Reset() {
	*x = CParental_LockClient_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_LockClient_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_LockClient_Request) ProtoMessage() {}

func (x *CParental_LockClient_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_LockClient_Request.ProtoReflect.Descriptor instead.
func (*CParental_LockClient_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{16}
}

func (x *CParental_LockClient_Request) GetSession() string {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return ""
}

type CParental_LockClient_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_LockClient_Response) Reset() {
	*x = CParental_LockClient_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_LockClient_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_LockClient_Response) ProtoMessage() {}

func (x *CParental_LockClient_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_LockClient_Response.ProtoReflect.Descriptor instead.
func (*CParental_LockClient_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{17}
}

type CParental_RequestRecoveryCode_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_RequestRecoveryCode_Request) Reset() {
	*x = CParental_RequestRecoveryCode_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_RequestRecoveryCode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_RequestRecoveryCode_Request) ProtoMessage() {}

func (x *CParental_RequestRecoveryCode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_RequestRecoveryCode_Request.ProtoReflect.Descriptor instead.
func (*CParental_RequestRecoveryCode_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{18}
}

type CParental_RequestRecoveryCode_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_RequestRecoveryCode_Response) Reset() {
	*x = CParental_RequestRecoveryCode_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_RequestRecoveryCode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_RequestRecoveryCode_Response) ProtoMessage() {}

func (x *CParental_RequestRecoveryCode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_RequestRecoveryCode_Response.ProtoReflect.Descriptor instead.
func (*CParental_RequestRecoveryCode_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{19}
}

type CParental_DisableWithRecoveryCode_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCode  *uint32                `protobuf:"varint,1,opt,name=recovery_code,json=recoveryCode" json:"recovery_code,omitempty"`
	Steamid       *uint64                `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_DisableWithRecoveryCode_Request) Reset() {
	*x = CParental_DisableWithRecoveryCode_Request{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_DisableWithRecoveryCode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_DisableWithRecoveryCode_Request) ProtoMessage() {}

func (x *CParental_DisableWithRecoveryCode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_DisableWithRecoveryCode_Request.ProtoReflect.Descriptor instead.
func (*CParental_DisableWithRecoveryCode_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{20}
}

func (x *CParental_DisableWithRecoveryCode_Request) GetRecoveryCode() uint32 {
	if x != nil && x.RecoveryCode != nil {
		return *x.RecoveryCode
	}
	return 0
}

func (x *CParental_DisableWithRecoveryCode_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

type CParental_DisableWithRecoveryCode_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_DisableWithRecoveryCode_Response) Reset() {
	*x = CParental_DisableWithRecoveryCode_Response{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_DisableWithRecoveryCode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_DisableWithRecoveryCode_Response) ProtoMessage() {}

func (x *CParental_DisableWithRecoveryCode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_DisableWithRecoveryCode_Response.ProtoReflect.Descriptor instead.
func (*CParental_DisableWithRecoveryCode_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{21}
}

type CParental_ParentalSettingsChange_Notification struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SerializedSettings []byte                 `protobuf:"bytes,1,opt,name=serialized_settings,json=serializedSettings" json:"serialized_settings,omitempty"`
	Signature          []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Password           *string                `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Sessionid          *string                `protobuf:"bytes,4,opt,name=sessionid" json:"sessionid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CParental_ParentalSettingsChange_Notification) Reset() {
	*x = CParental_ParentalSettingsChange_Notification{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ParentalSettingsChange_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ParentalSettingsChange_Notification) ProtoMessage() {}

func (x *CParental_ParentalSettingsChange_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ParentalSettingsChange_Notification.ProtoReflect.Descriptor instead.
func (*CParental_ParentalSettingsChange_Notification) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{22}
}

func (x *CParental_ParentalSettingsChange_Notification) GetSerializedSettings() []byte {
	if x != nil {
		return x.SerializedSettings
	}
	return nil
}

func (x *CParental_ParentalSettingsChange_Notification) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CParental_ParentalSettingsChange_Notification) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_ParentalSettingsChange_Notification) GetSessionid() string {
	if x != nil && x.Sessionid != nil {
		return *x.Sessionid
	}
	return ""
}

type CParental_ParentalUnlock_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      *string                `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Sessionid     *string                `protobuf:"bytes,2,opt,name=sessionid" json:"sessionid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_ParentalUnlock_Notification) Reset() {
	*x = CParental_ParentalUnlock_Notification{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ParentalUnlock_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ParentalUnlock_Notification) ProtoMessage() {}

func (x *CParental_ParentalUnlock_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ParentalUnlock_Notification.ProtoReflect.Descriptor instead.
func (*CParental_ParentalUnlock_Notification) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{23}
}

func (x *CParental_ParentalUnlock_Notification) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CParental_ParentalUnlock_Notification) GetSessionid() string {
	if x != nil && x.Sessionid != nil {
		return *x.Sessionid
	}
	return ""
}

type CParental_ParentalLock_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessionid     *string                `protobuf:"bytes,1,opt,name=sessionid" json:"sessionid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CParental_ParentalLock_Notification) Reset() {
	*x = CParental_ParentalLock_Notification{}
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CParental_ParentalLock_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CParental_ParentalLock_Notification) ProtoMessage() {}

func (x *CParental_ParentalLock_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_parental_steamclient_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CParental_ParentalLock_Notification.ProtoReflect.Descriptor instead.
func (*CParental_ParentalLock_Notification) Descriptor() ([]byte, []int) {
	return file_steammessages_parental_steamclient_proto_rawDescGZIP(), []int{24}
}

func (x *CParental_ParentalLock_Notification) GetSessionid() string {
	if x != nil && x.Sessionid != nil {
		return *x.Sessionid
	}
	return ""
}

var File_steammessages_parental_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_parental_steamclient_proto_rawDesc = "" +
	"\n" +
	"(steammessages_parental.steamclient.proto\x1a,steammessages_unified_base.steamclient.proto\"B\n" +
	"\vParentalApp\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x02 \x01(\bR\tisAllowed\"\xfa\x03\n" +
	"\x10ParentalSettings\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12&\n" +
	"\x0fapplist_base_id\x18\x02 \x01(\rR\rapplistBaseId\x128\n" +
	"\x18applist_base_description\x18\x03 \x01(\tR\x16applistBaseDescription\x12/\n" +
	"\fapplist_base\x18\x04 \x03(\v2\f.ParentalAppR\vapplistBase\x123\n" +
	"\x0eapplist_custom\x18\x05 \x03(\v2\f.ParentalAppR\rapplistCustom\x12*\n" +
	"\x10passwordhashtype\x18\x06 \x01(\rR\x10passwordhashtype\x12\x12\n" +
	"\x04salt\x18\a \x01(\fR\x04salt\x12\"\n" +
	"\fpasswordhash\x18\b \x01(\fR\fpasswordhash\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\t \x01(\bR\tisEnabled\x12)\n" +
	"\x10enabled_features\x18\n" +
	" \x01(\rR\x0fenabledFeatures\x12%\n" +
	"\x0erecovery_email\x18\v \x01(\tR\rrecoveryEmail\x12/\n" +
	"\x14is_site_license_lock\x18\f \x01(\bR\x11isSiteLicenseLock\"\xcd\x01\n" +
	"(CParental_EnableParentalSettings_Request\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12-\n" +
	"\bsettings\x18\x02 \x01(\v2\x11.ParentalSettingsR\bsettings\x12\x1c\n" +
	"\tsessionid\x18\x03 \x01(\tR\tsessionid\x12\x1e\n" +
	"\n" +
	"enablecode\x18\x04 \x01(\rR\n" +
	"enablecode\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\"+\n" +
	")CParental_EnableParentalSettings_Response\"a\n" +
	")CParental_DisableParentalSettings_Request\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\",\n" +
	"*CParental_DisableParentalSettings_Response\"A\n" +
	"%CParental_GetParentalSettings_Request\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\"W\n" +
	"&CParental_GetParentalSettings_Response\x12-\n" +
	"\bsettings\x18\x01 \x01(\v2\x11.ParentalSettingsR\bsettings\"I\n" +
	"+CParental_GetSignedParentalSettings_Request\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\"}\n" +
	",CParental_GetSignedParentalSettings_Response\x12/\n" +
	"\x13serialized_settings\x18\x01 \x01(\fR\x12serializedSettings\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xcd\x01\n" +
	"%CParental_SetParentalSettings_Request\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12-\n" +
	"\bsettings\x18\x02 \x01(\v2\x11.ParentalSettingsR\bsettings\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12\x1c\n" +
	"\tsessionid\x18\x04 \x01(\tR\tsessionid\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\"(\n" +
	"&CParental_SetParentalSettings_Response\"D\n" +
	"\x1fCParental_ValidateToken_Request\x12!\n" +
	"\funlock_token\x18\x01 \x01(\tR\vunlockToken\"\"\n" +
	" CParental_ValidateToken_Response\"\x8f\x01\n" +
	"\"CParental_ValidatePassword_Request\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x123\n" +
	"\x16send_unlock_on_success\x18\x03 \x01(\bR\x13sendUnlockOnSuccess\";\n" +
	"#CParental_ValidatePassword_Response\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"8\n" +
	"\x1cCParental_LockClient_Request\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x1f\n" +
	"\x1dCParental_LockClient_Response\"'\n" +
	"%CParental_RequestRecoveryCode_Request\"(\n" +
	"&CParental_RequestRecoveryCode_Response\"j\n" +
	")CParental_DisableWithRecoveryCode_Request\x12#\n" +
	"\rrecovery_code\x18\x01 \x01(\rR\frecoveryCode\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\",\n" +
	"*CParental_DisableWithRecoveryCode_Response\"\xb8\x01\n" +
	"-CParental_ParentalSettingsChange_Notification\x12/\n" +
	"\x13serialized_settings\x18\x01 \x01(\fR\x12serializedSettings\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1c\n" +
	"\tsessionid\x18\x04 \x01(\tR\tsessionid\"a\n" +
	"%CParental_ParentalUnlock_Notification\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1c\n" +
	"\tsessionid\x18\x02 \x01(\tR\tsessionid\"C\n" +
	"#CParental_ParentalLock_Notification\x12\x1c\n" +
	"\tsessionid\x18\x01 \x01(\tR\tsessionid2\xd2\x0e\n" +
	"\bParental\x12\xd0\x01\n" +
	"\x16EnableParentalSettings\x12).CParental_EnableParentalSettings_Request\x1a*.CParental_EnableParentalSettings_Response\"_\x82\xb5\x18[Enable parental settings for the logged in account, optionally setting the current settings\x12\xab\x01\n" +
	"\x17DisableParentalSettings\x12*.CParental_DisableParentalSettings_Request\x1a+.CParental_DisableParentalSettings_Response\"7\x82\xb5\x183Disable parental settings for the logged in account\x12\xa7\x01\n" +
	"\x13GetParentalSettings\x12&.CParental_GetParentalSettings_Request\x1a'.CParental_GetParentalSettings_Response\"?\x82\xb5\x18;Get the current parental settings for the logged in account\x12\xe8\x01\n" +
	"\x19GetSignedParentalSettings\x12,.CParental_GetSignedParentalSettings_Request\x1a-.CParental_GetSignedParentalSettings_Response\"n\x82\xb5\x18jGet the current parental settings for the logged in account in a form that can by verified by the receiver\x12\xa7\x01\n" +
	"\x13SetParentalSettings\x12&.CParental_SetParentalSettings_Request\x1a'.CParental_SetParentalSettings_Response\"?\x82\xb5\x18;Set the current parental settings for the logged in account\x12\xa7\x01\n" +
	"\rValidateToken\x12 .CParental_ValidateToken_Request\x1a!.CParental_ValidateToken_Response\"Q\x82\xb5\x18MCheck if the given parental unlock token is correct for the logged in account\x12\xb7\x01\n" +
	"\x10ValidatePassword\x12#.CParental_ValidatePassword_Request\x1a$.CParental_ValidatePassword_Response\"X\x82\xb5\x18TValidate the plaintext password for the logged in account and return an unlock token\x12\x8f\x01\n" +
	"\n" +
	"LockClient\x12\x1d.CParental_LockClient_Request\x1a\x1e.CParental_LockClient_Response\"B\x82\xb5\x18>Notify connected clients that a lock has occurred in a browser\x12\xc3\x01\n" +
	"\x13RequestRecoveryCode\x12&.CParental_RequestRecoveryCode_Request\x1a'.CParental_RequestRecoveryCode_Response\"[\x82\xb5\x18WRequest a recovery code be sent to the recovery email address for the specified account\x12\xaa\x01\n" +
	"\x17DisableWithRecoveryCode\x12*.CParental_DisableWithRecoveryCode_Request\x1a+.CParental_DisableWithRecoveryCode_Response\"6\x82\xb5\x182Attempt a recovery unlock on the specified account\x1a\x1d\x82\xb5\x18\x19Parental settings service2\x86\x04\n" +
	"\x0eParentalClient\x12\x9c\x01\n" +
	"\x14NotifySettingsChange\x12..CParental_ParentalSettingsChange_Notification\x1a\v.NoResponse\"G\x82\xb5\x18CNotification from server to client of a change in parental settings\x12\x94\x01\n" +
	"\fNotifyUnlock\x12&.CParental_ParentalUnlock_Notification\x1a\v.NoResponse\"O\x82\xb5\x18KNotification from server to client that an unlock has occurred in a browser\x12\x8d\x01\n" +
	"\n" +
	"NotifyLock\x12$.CParental_ParentalLock_Notification\x1a\v.NoResponse\"L\x82\xb5\x18HNotification from server to client that a lock has occurred in a browser\x1a.\x82\xb5\x18&Parental settings client notifications\xc0\xb5\x18\x02B\x03\x80\x01\x01"

var (
	file_steammessages_parental_steamclient_proto_rawDescOnce sync.Once
	file_steammessages_parental_steamclient_proto_rawDescData []byte
)

func file_steammessages_parental_steamclient_proto_rawDescGZIP() []byte {
	file_steammessages_parental_steamclient_proto_rawDescOnce.Do(func() {
		file_steammessages_parental_steamclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_parental_steamclient_proto_rawDesc), len(file_steammessages_parental_steamclient_proto_rawDesc)))
	})
	return file_steammessages_parental_steamclient_proto_rawDescData
}

var file_steammessages_parental_steamclient_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_steammessages_parental_steamclient_proto_goTypes = []any{
	(*ParentalApp)(nil),                                             // 0: ParentalApp
	(*ParentalSettings)(nil),                                        // 1: ParentalSettings
	(*CParental_EnableParentalSettings_Request)(nil),                // 2: CParental_EnableParentalSettings_Request
	(*CParental_EnableParentalSettings_Response)(nil),               // 3: CParental_EnableParentalSettings_Response
	(*CParental_DisableParentalSettings_Request)(nil),               // 4: CParental_DisableParentalSettings_Request
	(*CParental_DisableParentalSettings_Response)(nil),              // 5: CParental_DisableParentalSettings_Response
	(*CParental_GetParentalSettings_Request)(nil),                   // 6: CParental_GetParentalSettings_Request
	(*CParental_GetParentalSettings_Response)(nil),                  // 7: CParental_GetParentalSettings_Response
	(*CParental_GetSignedParentalSettings_Request)(nil),             // 8: CParental_GetSignedParentalSettings_Request
	(*CParental_GetSignedParentalSettings_Response)(nil),            // 9: CParental_GetSignedParentalSettings_Response
	(*CParental_SetParentalSettings_Request)(nil),                   // 10: CParental_SetParentalSettings_Request
	(*CParental_SetParentalSettings_Response)(nil),                  // 11: CParental_SetParentalSettings_Response
	(*CParental_ValidateToken_Request)(nil),                         // 12: CParental_ValidateToken_Request
	(*CParental_ValidateToken_Response)(nil),                        // 13: CParental_ValidateToken_Response
	(*CParental_ValidatePassword_Request)(nil),                      // 14: CParental_ValidatePassword_Request
	(*CParental_ValidatePassword_Response)(nil),                     // 15: CParental_ValidatePassword_Response
	(*CParental_LockClient_Request)(nil),                            // 16: CParental_LockClient_Request
	(*CParental_LockClient_Response)(nil),                           // 17: CParental_LockClient_Response
	(*CParental_RequestRecoveryCode_Request)(nil),                   // 18: CParental_RequestRecoveryCode_Request
	(*CParental_RequestRecoveryCode_Response)(nil),                  // 19: CParental_RequestRecoveryCode_Response
	(*CParental_DisableWithRecoveryCode_Request)(nil),               // 20: CParental_DisableWithRecoveryCode_Request
	(*CParental_DisableWithRecoveryCode_Response)(nil),              // 21: CParental_DisableWithRecoveryCode_Response
	(*CParental_ParentalSettingsChange_Notification)(nil),           // 22: CParental_ParentalSettingsChange_Notification
	(*CParental_ParentalUnlock_Notification)(nil),                   // 23: CParental_ParentalUnlock_Notification
	(*CParental_ParentalLock_Notification)(nil),                     // 24: CParental_ParentalLock_Notification
	(*NoResponse)(nil), // 25: NoResponse
}
var file_steammessages_parental_steamclient_proto_depIdxs = []int32{
	0,  // 0: ParentalSettings.applist_base:type_name -> ParentalApp
	0,  // 1: ParentalSettings.applist_custom:type_name -> ParentalApp
	1,  // 2: CParental_EnableParentalSettings_Request.settings:type_name -> ParentalSettings
	1,  // 3: CParental_GetParentalSettings_Response.settings:type_name -> ParentalSettings
	1,  // 4: CParental_SetParentalSettings_Request.settings:type_name -> ParentalSettings
	2,  // 5: Parental.EnableParentalSettings:input_type -> CParental_EnableParentalSettings_Request
	4,  // 6: Parental.DisableParentalSettings:input_type -> CParental_DisableParentalSettings_Request
	6,  // 7: Parental.GetParentalSettings:input_type -> CParental_GetParentalSettings_Request
	8,  // 8: Parental.GetSignedParentalSettings:input_type -> CParental_GetSignedParentalSettings_Request
	10, // 9: Parental.SetParentalSettings:input_type -> CParental_SetParentalSettings_Request
	12, // 10: Parental.ValidateToken:input_type -> CParental_ValidateToken_Request
	14, // 11: Parental.ValidatePassword:input_type -> CParental_ValidatePassword_Request
	16, // 12: Parental.LockClient:input_type -> CParental_LockClient_Request
	18, // 13: Parental.RequestRecoveryCode:input_type -> CParental_RequestRecoveryCode_Request
	20, // 14: Parental.DisableWithRecoveryCode:input_type -> CParental_DisableWithRecoveryCode_Request
	22, // 15: ParentalClient.NotifySettingsChange:input_type -> CParental_ParentalSettingsChange_Notification
	23, // 16: ParentalClient.NotifyUnlock:input_type -> CParental_ParentalUnlock_Notification
	24, // 17: ParentalClient.NotifyLock:input_type -> CParental_ParentalLock_Notification
	3,  // 18: Parental.EnableParentalSettings:output_type -> CParental_EnableParentalSettings_Response
	5,  // 19: Parental.DisableParentalSettings:output_type -> CParental_DisableParentalSettings_Response
	7,  // 20: Parental.GetParentalSettings:output_type -> CParental_GetParentalSettings_Response
	9,  // 21: Parental.GetSignedParentalSettings:output_type -> CParental_GetSignedParentalSettings_Response
	11, // 22: Parental.SetParentalSettings:output_type -> CParental_SetParentalSettings_Response
	13, // 23: Parental.ValidateToken:output_type -> CParental_ValidateToken_Response
	15, // 24: Parental.ValidatePassword:output_type -> CParental_ValidatePassword_Response
	17, // 25: Parental.LockClient:output_type -> CParental_LockClient_Response
	19, // 26: Parental.RequestRecoveryCode:output_type -> CParental_RequestRecoveryCode_Response
	21, // 27: Parental.DisableWithRecoveryCode:output_type -> CParental_DisableWithRecoveryCode_Response
	25, // 28: ParentalClient.NotifySettingsChange:output_type -> NoResponse
	25, // 29: ParentalClient.NotifyUnlock:output_type -> NoResponse
	25, // 30: ParentalClient.NotifyLock:output_type -> NoResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_steammessages_parental_steamclient_proto_init() }
func file_steammessages_parental_steamclient_proto_init() {
	if File_steammessages_parental_steamclient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_parental_steamclient_proto_rawDesc), len(file_steammessages_parental_steamclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_steammessages_parental_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_parental_steamclient_proto_depIdxs,
		MessageInfos:      file_steammessages_parental_steamclient_proto_msgTypes,
	}.Build()
	File_steammessages_parental_steamclient_proto = out.File
	file_steammessages_parental_steamclient_proto_goTypes = nil
	file_steammessages_parental_steamclient_proto_depIdxs = nil
}
